## Sommaire

* [Importation des librairies](#import)


* [Question 1: Population en 2013](#Question1)


* [Question 2: Identifiez les redondances](#Question2)


* [Question 3: Calculez pour chaque pays et chaque produit la disponibilité alimentaire en kcal puis en kg de protéines](#Question3)


* [Question 4: Ratios énergie /poids et calories/poids](#Question4)


* [Question 5: Citez 5 aliments parmi les 20 plus caloriques grâce au ratio énergie/poids](#Question5)


* [Question 6: Calculez la disponibilité intérieure mondiale en kcal pour tous les produits végétaux](#Question6)


* [Question 7: Nombre d'humains pouvant être nourris par la quantité de produits végétaux disponibles](#Question7)


* [Question 8: Combien d'humains pourraient être nourris si toute la disponibilité alimentaire végétale perdue ou destinée aux animaux étaient utilisés pour de la nourriture?](#Question8)


* [Question 9: Combien d'humains pourraient être nourris avec la disponibilité alimentaire mondiale?](#Question9)


* [Question 10: Quelle proportion de la population mondiale est considérée comme étant en sous-nutrition ?](#Question10)


* [Question 11: Quelle proportion des céréales destinées à l'alimentation a pour fin l'alimentation animale ?](#Question11)


* [Question 12: Donnez les 3 produits qui ont la plus grande valeur pour chacun des 2 ratios](#Question12)


* [Question 13: Combien de tonnes de céréales pourraient être libérées si les USA diminuaient de 10% leur production de produits destinés à l'alimentation animale?](#Question13)


* [Question 14: En Thaïlande, quelle proportion de manioc est exportée et quelle est la proportion de personnes en sous-nutrtion?](#Question14)


* [Question 15: Proposez une clé primaire pertinente pour la table 'population'](#Question15)


* [Question 16: Proposez une clé primaire pertinente pour la table 'dispo_alim'](#Question16)


* [Question 17: Proposez une clé primaire pertinente pour la table 'equilibre_prod'](#Question17)


* [Question 18: Proposez une clé primaire pour la table 'sous_nutrition'](#Question18)


* [Question 19: Écrivez des requêtes SQL](#Question19)


* [Question 20: Supposez quelles sont les "autres utilisations" possibles ?](#Question20)

## Importation des librairies  <a class='anchor' id='import'></a>

In [1]:
# Importation des librairies
import pandas as pd
import numpy as np

In [2]:
# Masquer les messages d'erreurs mineures
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Chargement des bases de données
population = pd.read_csv('data/fr_population.csv')
animaux = pd.read_csv('data/fr_animaux.csv')
cereales = pd.read_csv('data/fr_cereales.csv')
sous_alim = pd.read_csv('data/fr_sousalimentation.csv')
vegetaux = pd.read_csv('data/fr_vegetaux.csv')

<a class='anchor' id='Question1'></a>
## Question 1: Population en 2013

In [4]:
population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175 entries, 0 to 174
Data columns (total 14 columns):
Code Domaine              175 non-null object
Domaine                   175 non-null object
Code zone                 175 non-null int64
Zone                      175 non-null object
Code Élément              175 non-null int64
Élément                   175 non-null object
Code Produit              175 non-null int64
Produit                   175 non-null object
Code année                175 non-null int64
Année                     175 non-null int64
Unité                     175 non-null object
Valeur                    175 non-null int64
Symbole                   1 non-null object
Description du Symbole    175 non-null object
dtypes: int64(6), object(8)
memory usage: 19.2+ KB

#### Avec seulement 1 objet non-nul, la colonne 'Symbole' présente une exception

In [5]:
# Recherche des données dont la valeur 'Symbole' est non-nulle
population.loc[population.Symbole.notnull()]

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
33,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,351,Chine,511,Population totale,2501,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,..."

In [6]:
# Recherche des données relatives à la Chine
population.loc[population.Zone.str.contains('Chine')]

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
33,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,351,Chine,511,Population totale,2501,Population,2013,2013,1000 personnes,1416667,A,"Agrégat, peut inclure des données officielles,..."
34,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,96,Chine - RAS de Hong-Kong,511,Population totale,2501,Population,2013,2013,1000 personnes,7204,NaN,Donnée officielle
35,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,128,Chine - RAS de Macao,511,Population totale,2501,Population,2013,2013,1000 personnes,566,NaN,Donnée officielle
36,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,41,"Chine, continentale",511,Population totale,2501,Population,2013,2013,1000 personnes,1385567,NaN,Donnée officielle
37,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,214,"Chine, Taiwan Province de",511,Population totale,2501,Population,2013,2013,1000 personnes,23330,NaN,Donnée officielle

#### Suppression de la ligne dédiée à la 'Chine'

In [7]:
population.drop(population.loc[population.Zone == 'Chine'].index, inplace=True)
population.loc[population.Zone.str.contains('Chine')]

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
34,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,96,Chine - RAS de Hong-Kong,511,Population totale,2501,Population,2013,2013,1000 personnes,7204,NaN,Donnée officielle
35,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,128,Chine - RAS de Macao,511,Population totale,2501,Population,2013,2013,1000 personnes,566,NaN,Donnée officielle
36,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,41,"Chine, continentale",511,Population totale,2501,Population,2013,2013,1000 personnes,1385567,NaN,Donnée officielle
37,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,214,"Chine, Taiwan Province de",511,Population totale,2501,Population,2013,2013,1000 personnes,23330,NaN,Donnée officielle

#### Nettoyage du tableau 'population'

In [8]:
# Suppression des colonnes inutiles
population.drop(columns=['Code Domaine', 'Domaine', 'Code Élément', 'Élément', 'Produit', 'Code Produit', 'Code année', 'Unité', 'Symbole', 'Description du Symbole'], inplace=True)

# Colonne 'Valeur' renommée 'Population'
population.rename(columns={'Valeur': 'Population'}, inplace=True)

# Mesure de la colonne 'Population' par unités et non plus par milliers
population['Population'] = population['Population'] * 1e3

population.head()

   Code zone            Zone  Année  Population
0          2     Afghanistan   2013  30552000.0
1        202  Afrique du Sud   2013  52776000.0
2          3         Albanie   2013   3173000.0
3          4         Algérie   2013  39208000.0
4         79       Allemagne   2013  82727000.0

In [9]:
population_mondiale = population['Population'].sum()
print(population_mondiale)

6997326000.0

#### En 2013, la population mondiale s'élevait à 6 997 326 000 d'habitants

<a class='anchor' id='Question2'></a>
## Question 2: Identifiez les redondances

#### Concaténation des tables 'vegetaux' et 'animaux'

In [10]:
# Création d'une colonne permettant d'identifier la table d'origine
vegetaux['Origine'] = 'Vegetaux'
animaux['Origine'] = 'Animaux'

# Concaténation des tables 'animaux' et 'vegetaux'
alimentation = pd.concat([animaux, vegetaux])
alimentation.head()

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Origine
0,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5511,Production,2731,Viande de Bovins,2013,2013,Milliers de tonnes,134.00,S,Données standardisées,Animaux
1,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5611,Importations - Quantité,2731,Viande de Bovins,2013,2013,Milliers de tonnes,6.00,S,Données standardisées,Animaux
2,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5301,Disponibilité intérieure,2731,Viande de Bovins,2013,2013,Milliers de tonnes,140.00,S,Données standardisées,Animaux
3,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,5142,Nourriture,2731,Viande de Bovins,2013,2013,Milliers de tonnes,140.00,S,Données standardisées,Animaux
4,FBSH,Bilans Alimentaire (Ancienne méthodologie et p...,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2731,Viande de Bovins,2013,2013,kg,4.59,Fc,Donnée calculée,Animaux

##### Nettoyage de la table 'alimentation'

In [11]:
alimentation.drop(columns=['Code Domaine', 'Domaine', 'Code année', 'Symbole', 'Description du Symbole'], inplace=True)
alimentation.drop(alimentation.loc[alimentation.Zone == 'Chine'].index, inplace=True)
alimentation.head()

,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Année,Unité,Valeur,Origine
0,2,Afghanistan,5511,Production,2731,Viande de Bovins,2013,Milliers de tonnes,134.00,Animaux
1,2,Afghanistan,5611,Importations - Quantité,2731,Viande de Bovins,2013,Milliers de tonnes,6.00,Animaux
2,2,Afghanistan,5301,Disponibilité intérieure,2731,Viande de Bovins,2013,Milliers de tonnes,140.00,Animaux
3,2,Afghanistan,5142,Nourriture,2731,Viande de Bovins,2013,Milliers de tonnes,140.00,Animaux
4,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2731,Viande de Bovins,2013,kg,4.59,Animaux

#### Fusion des tables 'alimentation' et 'population'

In [12]:
alimentation = pd.merge(alimentation, population, on=['Code zone', 'Zone', 'Année'])
alimentation.head()

,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Année,Unité,Valeur,Origine,Population
0,2,Afghanistan,5511,Production,2731,Viande de Bovins,2013,Milliers de tonnes,134.00,Animaux,30552000.0
1,2,Afghanistan,5611,Importations - Quantité,2731,Viande de Bovins,2013,Milliers de tonnes,6.00,Animaux,30552000.0
2,2,Afghanistan,5301,Disponibilité intérieure,2731,Viande de Bovins,2013,Milliers de tonnes,140.00,Animaux,30552000.0
3,2,Afghanistan,5142,Nourriture,2731,Viande de Bovins,2013,Milliers de tonnes,140.00,Animaux,30552000.0
4,2,Afghanistan,645,Disponibilité alimentaire en quantité (kg/pers...,2731,Viande de Bovins,2013,kg,4.59,Animaux,30552000.0

#### Table pivot de la disponibilité alimentaire selon le pays et les diverses utilisations ('Élément')

In [13]:
dispo_alim = alimentation.pivot_table('Valeur', ['Zone', 'Population', 'Code Produit', 'Produit', 'Origine'], 'Élément', aggfunc="sum").reset_index()
dispo_alim.head()

Élément,Zone,Population,Code Produit,Produit,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
0,Afghanistan,30552000.0,2511,Blé,Vegetaux,NaN,NaN,1369.0,160.23,4.69,36.91,5992.0,NaN,1173.0,4895.0,775.0,5169.0,322.0,NaN,-350.0
1,Afghanistan,30552000.0,2513,Orge,Vegetaux,360.0,NaN,26.0,2.92,0.24,0.79,524.0,NaN,10.0,89.0,52.0,514.0,22.0,NaN,0.0
2,Afghanistan,30552000.0,2514,Maïs,Vegetaux,200.0,NaN,21.0,2.50,0.30,0.56,313.0,0.0,1.0,76.0,31.0,312.0,5.0,NaN,NaN
3,Afghanistan,30552000.0,2517,Millet,Vegetaux,NaN,NaN,3.0,0.40,0.02,0.08,13.0,NaN,NaN,12.0,1.0,13.0,0.0,NaN,NaN
4,Afghanistan,30552000.0,2520,"Céréales, Autres",Vegetaux,NaN,NaN,0.0,0.00,0.00,0.00,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN

#### L'exemple du blé en France

Production + Importations + Variation de stock - Exportations

= Disponibilité intérieure 

= Aliments pour animaux + Semences + Pertes + Traitement + Autres utilisations (non alimentaire) + Nourriture

#### Identification des redondances:

In [14]:
blé_France = dispo_alim.loc[(dispo_alim.Zone == 'France') & (dispo_alim.Produit == 'Blé')]
blé_France

Élément,Zone,Population,Code Produit,Produit,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
4813,France,64291000.0,2511,Blé,Vegetaux,7822.0,2824.0,811.0,108.43,4.2,25.99,20298.0,21502.0,2055.0,6971.0,358.0,38614.0,748.0,1575.0,1131.0

In [15]:
# Somme de Production + Importations + Variation de stock - Exportations
blé_France.loc[:, 'Production'] + blé_France.loc[:, 'Importations - Quantité'] + blé_France.loc[:, 'Variation de stock'] - blé_France.loc[:, 'Exportations - Quantité']

4813    20298.0
dtype: float64

In [16]:
# Disponibilité intérieure
blé_France['Disponibilité intérieure']

4813    20298.0
Name: Disponibilité intérieure, dtype: float64

In [17]:
# Somme de Aliments pour animaux + Semences + Pertes + Traitement + Autres utilisations + Nourriture
blé_France.loc[:,'Aliments pour animaux'] + blé_France.loc[:,'Semences'] + blé_France.loc[:,'Pertes'] + blé_France.loc[:,'Traitement'] + blé_France.loc[:,'Autres utilisations (non alimentaire)'] + blé_France.loc[:,'Nourriture']

4813    20298.0
dtype: float64

In [18]:
# Aggrégation des différents Eléments
alimentation.groupby('Élément')[['Valeur']].agg('sum')

                                                         Valeur
Élément
Aliments pour animaux                                1303595.00
Autres utilisations (non alimentaire)                 864490.00
Disponibilité alimentaire (Kcal/personne/jour)        491688.00
Disponibilité alimentaire en quantité (kg/perso...    120700.48
Disponibilité de matière grasse en quantité (g/...     14864.40
Disponibilité de protéines en quantité (g/perso...     13939.15
Disponibilité intérieure                             9841836.00
Exportations - Quantité                              1348019.00
Importations - Quantité                              1290977.00
Nourriture                                           4870986.00
Pertes                                                453441.00
Production                                          10004515.00
Semences                                              154672.00
Traitement                                           2204327.00
Variation de stock                                   -104556.00

<a class='anchor' id='Question3'></a>
## Question 3: Calculez (pour chaque pays et chaque produit) la disponibilité alimentaire en kcal puis en kg de protéines

#### Ajout des colonnes totalisant les disponibilités alimentaires par pays et produit en Kcal et en protéines

In [19]:
dispo_alim['Disponibilité alimentaire annuelle en Kcal'] = dispo_alim.loc[:, 'Disponibilité alimentaire (Kcal/personne/jour)'] * dispo_alim.loc[:, 'Population'] * 365
dispo_alim['Disponibilité de protéines annuelle en Kg'] = dispo_alim.loc[:, 'Disponibilité de protéines en quantité (g/personne/jour)'] / 1e3 * dispo_alim.loc[:, 'Population'] * 365
dispo_alim

Élément,Zone,Population,Code Produit,Produit,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,Disponibilité alimentaire annuelle en Kcal,Disponibilité de protéines annuelle en Kg
0,Afghanistan,30552000.0,2511,Blé,Vegetaux,NaN,NaN,1369.0,160.23,4.69,...,NaN,1173.0,4895.0,775.0,5169.0,322.0,NaN,-350.0,1.526638e+13,4.116011e+08
1,Afghanistan,30552000.0,2513,Orge,Vegetaux,360.0,NaN,26.0,2.92,0.24,...,NaN,10.0,89.0,52.0,514.0,22.0,NaN,0.0,2.899385e+11,8.809669e+06
2,Afghanistan,30552000.0,2514,Maïs,Vegetaux,200.0,NaN,21.0,2.50,0.30,...,0.0,1.0,76.0,31.0,312.0,5.0,NaN,NaN,2.341811e+11,6.244829e+06
3,Afghanistan,30552000.0,2517,Millet,Vegetaux,NaN,NaN,3.0,0.40,0.02,...,NaN,NaN,12.0,1.0,13.0,0.0,NaN,NaN,3.345444e+10,8.921184e+05
4,Afghanistan,30552000.0,2520,"Céréales, Autres",Vegetaux,NaN,NaN,0.0,0.00,0.00,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00
5,Afghanistan,30552000.0,2531,Pommes de Terre,Vegetaux,NaN,NaN,15.0,7.53,0.04,...,41.0,0.0,230.0,9.0,303.0,23.0,NaN,NaN,1.672722e+11,2.787870e+06
6,Afghanistan,30552000.0,2536,"Sucre, canne",Vegetaux,81.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,90.0,NaN,9.0,NaN,NaN,NaN
7,Afghanistan,30552000.0,2537,"Sucre, betterave",Vegetaux,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,15.0,NaN,15.0,NaN,NaN,NaN
8,Afghanistan,30552000.0,2542,Sucre Eq Brut,Vegetaux,NaN,NaN,84.0,8.35,NaN,...,NaN,271.0,255.0,NaN,2.0,NaN,NaN,-19.0,9.367243e+11,NaN
9,Afghanistan,30552000.0,2543,Edulcorants Autres,Vegetaux,NaN,NaN,2.0,0.53,NaN,...,NaN,16.0,16.0,NaN,NaN,NaN,NaN,NaN,2.230296e+10,NaN
10,Afghanistan,30552000.0,2549,Légumineuses Autres,Vegetaux,4.0,NaN,23.0,2.44,0.14,...,0.0,26.0,74.0,3.0,60.0,5.0,NaN,NaN,2.564840e+11,1.739631e+07
11,Afghanistan,30552000.0,2551,Noix,Vegetaux,NaN,NaN,12.0,1.45,1.07,...,12.0,NaN,44.0,NaN,56.0,NaN,NaN,NaN,1.338178e+11,4.237562e+06
12,Afghanistan,30552000.0,2557,Graines de tournesol,Vegetaux,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,0.0,3.0,NaN,NaN,NaN
13,Afghanistan,30552000.0,2559,Graines de coton,Vegetaux,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,27.0,1.0,26.0,NaN,NaN,NaN
14,Afghanistan,30552000.0,2560,Coco (Incl Coprah),Vegetaux,NaN,NaN,0.0,0.00,0.00,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00
15,Afghanistan,30552000.0,2561,Sésame,Vegetaux,NaN,NaN,9.0,0.52,0.77,...,11.0,NaN,16.0,1.0,32.0,1.0,4.0,0.0,1.003633e+11,3.010900e+06
16,Afghanistan,30552000.0,2563,Olives,Vegetaux,NaN,NaN,0.0,0.06,0.03,...,0.0,NaN,2.0,0.0,7.0,NaN,4.0,NaN,0.000000e+00,0.000000e+00
17,Afghanistan,30552000.0,2570,"Plantes Oleiferes, Autre",Vegetaux,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,0.0,3.0,0.0,2.0,NaN,NaN,NaN
18,Afghanistan,30552000.0,2571,Huile de Soja,Vegetaux,NaN,NaN,13.0,0.53,1.46,...,NaN,16.0,16.0,NaN,NaN,NaN,NaN,NaN,1.449692e+11,NaN
19,Afghanistan,30552000.0,2572,Huile d'Arachide,Vegetaux,NaN,NaN,0.0,0.00,0.00,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN
20,Afghanistan,30552000.0,2573,Huile de Tournesol,Vegetaux,NaN,NaN,18.0,0.75,2.06,...,NaN,22.0,23.0,NaN,1.0,NaN,NaN,NaN,2.007266e+11,NaN
21,Afghanistan,30552000.0,2574,Huile de Colza&Moutarde,Vegetaux,NaN,NaN,2.0,0.07,0.18,...,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,2.230296e+10,NaN
22,Afghanistan,30552000.0,2575,Huile Graines de Coton,Vegetaux,NaN,1.0,3.0,0.12,0.34,...,NaN,NaN,4.0,NaN,5.0,NaN,NaN,NaN,3.345444e+10,NaN
23,Afghanistan,30552000.0,2577,Huile de Palme,Vegetaux,NaN,55.0,51.0,2.09,5.74,...,NaN,119.0,64.0,NaN,NaN,NaN,NaN,NaN,5.687255e+11,NaN
24,Afghanistan,30552000.0,2579,Huile de Sésame,Vegetaux,NaN,NaN,1.0,0.05,0.13,...,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,1.115148e+10,NaN
25,Afghanistan,30552000.0,2580,Huile d'Olive,Vegetaux,NaN,NaN,0.0,0.02,0.05,...,NaN,0.0,1.0,NaN,1.0,NaN,NaN,NaN,0.000000e+00,NaN
26,Afghanistan,30552000.0,2586,Huil Plantes Oleif Autr,Vegetaux,NaN,359.0,2.0,0.08,0.21,...,NaN,360.0,2.0,NaN,1.0,NaN,NaN,NaN,2.230296e+10,0.000000e+00
27,Afghanistan,30552000.0,2601,Tomates,Vegetaux,NaN,NaN,0.0,0.00,0.00,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00
28,Afghanistan,30552000.0,2605,"Légumes, Autres",Vegetaux,NaN,NaN,17.0,28.97,0.13,...,34.0,124.0,885.0,122.0,916.0,NaN,NaN,NaN,1.895752e+11,9.478758e+06
29,Afghanistan,30552000.0,2611,"Oranges, Mandarines",Vegetaux,NaN,NaN,4.0,4.75,0.01,...,0.0,139.0,145.0,0.0,6.0,NaN,NaN,NaN,4.460592e+10,7.806036e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15465,Îles Salomon,561000.0,2655,Vin,Vegetaux,NaN,NaN,0.0,0.07,NaN,...,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN
15466,Îles Salomon,561000.0,2656,Bière,Vegetaux,NaN,NaN,8.0,6.55,NaN,...,0.0,0.0,4.0,NaN,4.0,NaN,NaN,NaN,1.638120e+09,1.842885e+04
15467,Îles Salomon,561000.0,2657,Boissons Fermentés,Vegetaux,NaN,NaN,0.0,0.00,NaN,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN
15468,Îles Salomon,561000.0,2658,Boissons Alcooliques,Vegetaux,NaN,NaN,0.0,0.03,NaN,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.000000e+00,NaN
15469,Îles Salomon,561000.0,2659,"Alcool, non Comestible",Vegetaux,NaN,0.0,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15470,Îles Salomon,561000.0,2680,Aliments pour enfants,Vegetaux,NaN,NaN,0.0,0.03,NaN,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,2.047650e+03
15471,Îles Salomon,561000.0,2731,Viande de Bovins,Animaux,NaN,NaN,27.0,5.57,1.80,...,NaN,2.0,3.0,NaN,1.0,NaN,NaN,NaN,5.528655e+09,5.364843e+05
15472,Îles Salomon,561000.0,2732,Viande d'Ovins/Caprins,Animaux,NaN,NaN,1.0,0.14,0.09,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,2.047650e+08,1.023825e+04
15473,Îles Salomon,561000.0,2733,Viande de Suides,Animaux,NaN,NaN,45.0,4.70,4.28,...,NaN,0.0,3.0,NaN,2.0,NaN,NaN,NaN,9.214425e+09,2.887187e+05
15474,Îles Salomon,561000.0,2734,Viande de Volailles,Animaux,NaN,NaN,11.0,3.34,0.69,...,NaN,2.0,2.0,NaN,0.0,NaN,NaN,NaN,2.252415e+09,2.334321e+05
15475,Îles Salomon,561000.0,2735,"Viande, Autre",Animaux,NaN,NaN,0.0,0.06,NaN,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,8.190600e+03
15476,Îles Salomon,561000.0,2736,Abats Comestible,Animaux,NaN,NaN,2.0,0.64,0.05,...,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,4.095300e+08,6.552480e+04
15477,Îles Salomon,561000.0,2737,Graisses Animales Crue,Animaux,NaN,0.0,17.0,0.88,1.89,...,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,3.481005e+09,1.842885e+04
15478,Îles Salomon,561000.0,2740,"Beurre, Ghee",Animaux,NaN,NaN,1.0,0.07,0.17,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,2.047650e+08,NaN
15479,Îles Salomon,561000.0,2743,Crème,Animaux,NaN,NaN,0.0,0.02,0.01,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00
15480,Îles Salomon,561000.0,2744,Oeufs,Animaux,NaN,NaN,5.0,1.28,0.36,...,NaN,0.0,1.0,0.0,1.0,0.0,NaN,NaN,1.023825e+09,8.190600e+04
15481,Îles Salomon,561000.0,2761,Poissons Eau Douce,Animaux,NaN,0.0,0.0,0.00,0.00,...,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.000000e+00,0.000000e+00
15482,Îles Salomon,561000.0,2762,Perciform,Animaux,NaN,0.0,0.0,0.02,0.00,...,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000000e+00,0.000000e+00
15483,Îles Salomon,561000.0,2763,Poissons Pelagiques,Animaux,NaN,0.0,32.0,13.60,1.34,...,18.0,0.0,8.0,NaN,25.0,NaN,NaN,0.0,6.552480e+09,9.603479e+05
15484,Îles Salomon,561000.0,2764,"Poissons Marins, Autres",Animaux,NaN,0.0,36.0,19.01,1.33,...,2.0,2.0,11.0,NaN,10.0,NaN,NaN,0.0,7.371540e+09,1.140541e+06
15485,Îles Salomon,561000.0,2765,Crustacés,Animaux,NaN,0.0,0.0,0.03,0.00,...,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.000000e+00,2.047650e+03
15486,Îles Salomon,561000.0,2766,Cephalopodes,Animaux,NaN,0.0,0.0,0.00,0.00,...,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.000000e+00,0.000000e+00
15487,Îles Salomon,561000.0,2767,"Mollusques, Autres",Animaux,NaN,0.0,0.0,0.95,0.01,...,0.0,1.0,1.0,NaN,0.0,NaN,NaN,NaN,0.000000e+00,1.228590e+04
15488,Îles Salomon,561000.0,2769,Animaux Aquatiques Autre,Animaux,NaN,0.0,0.0,0.00,0.00,...,0.0,NaN,0.0,NaN,0.0,NaN,NaN,0.0,0.000000e+00,0.000000e+00
15489,Îles Salomon,561000.0,2775,Plantes Aquatiques,Animaux,NaN,8.0,0.0,0.00,0.00,...,0.0,0.0,0.0,NaN,8.0,NaN,NaN,NaN,0.000000e+00,0.000000e+00
15490,Îles Salomon,561000.0,2781,Huiles de Poissons,Animaux,NaN,0.0,0.0,0.00,0.00,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00
15491,Îles Salomon,561000.0,2782,Huiles de Foie de Poisso,Animaux,NaN,0.0,0.0,0.00,0.00,...,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00
15492,Îles Salomon,561000.0,2805,Riz (Eq Blanchi),Vegetaux,0.0,12.0,623.0,63.76,1.36,...,0.0,47.0,36.0,1.0,3.0,0.0,NaN,0.0,1.275686e+11,2.231938e+06
15493,Îles Salomon,561000.0,2848,Lait - Excl Beurre,Animaux,0.0,NaN,19.0,11.52,0.70,...,NaN,5.0,6.0,0.0,1.0,NaN,NaN,NaN,3.890535e+09,2.150033e+05
15494,Îles Salomon,561000.0,2899,Miscellanees,Vegetaux,NaN,NaN,3.0,NaN,0.04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.142950e+08,2.047650e+04

<a class='anchor' id='Question4'></a>
## Question 4: ratios énergie /poids et calories/poids

#### Calcul du ratio énergie/poids en kcal par kg

In [20]:
# Suppression des valeurs nulles de la disponibilité alimentaire en quantité (dénominateur)
dispo_alim.drop(dispo_alim.loc[(dispo_alim['Disponibilité alimentaire en quantité (kg/personne/an)'] == 0)].index, inplace=True)

# Ajout d'une colonne indiquant le ratio énergie/poids de chaque Élément
dispo_alim['Ratio Energie-Poids (kcal/kg)'] = dispo_alim.loc[:, 'Disponibilité alimentaire (Kcal/personne/jour)']  / dispo_alim.loc[:, 'Disponibilité alimentaire en quantité (kg/personne/an)'] * 365
dispo_alim

Élément,Zone,Population,Code Produit,Produit,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,Disponibilité alimentaire annuelle en Kcal,Disponibilité de protéines annuelle en Kg,Ratio Energie-Poids (kcal/kg)
0,Afghanistan,30552000.0,2511,Blé,Vegetaux,NaN,NaN,1369.0,160.23,4.69,...,1173.0,4895.0,775.0,5169.0,322.0,NaN,-350.0,1.526638e+13,4.116011e+08,3118.548337
1,Afghanistan,30552000.0,2513,Orge,Vegetaux,360.0,NaN,26.0,2.92,0.24,...,10.0,89.0,52.0,514.0,22.0,NaN,0.0,2.899385e+11,8.809669e+06,3250.000000
2,Afghanistan,30552000.0,2514,Maïs,Vegetaux,200.0,NaN,21.0,2.50,0.30,...,1.0,76.0,31.0,312.0,5.0,NaN,NaN,2.341811e+11,6.244829e+06,3066.000000
3,Afghanistan,30552000.0,2517,Millet,Vegetaux,NaN,NaN,3.0,0.40,0.02,...,NaN,12.0,1.0,13.0,0.0,NaN,NaN,3.345444e+10,8.921184e+05,2737.500000
5,Afghanistan,30552000.0,2531,Pommes de Terre,Vegetaux,NaN,NaN,15.0,7.53,0.04,...,0.0,230.0,9.0,303.0,23.0,NaN,NaN,1.672722e+11,2.787870e+06,727.091633
6,Afghanistan,30552000.0,2536,"Sucre, canne",Vegetaux,81.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,90.0,NaN,9.0,NaN,NaN,NaN,NaN
7,Afghanistan,30552000.0,2537,"Sucre, betterave",Vegetaux,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,15.0,NaN,15.0,NaN,NaN,NaN,NaN
8,Afghanistan,30552000.0,2542,Sucre Eq Brut,Vegetaux,NaN,NaN,84.0,8.35,NaN,...,271.0,255.0,NaN,2.0,NaN,NaN,-19.0,9.367243e+11,NaN,3671.856287
9,Afghanistan,30552000.0,2543,Edulcorants Autres,Vegetaux,NaN,NaN,2.0,0.53,NaN,...,16.0,16.0,NaN,NaN,NaN,NaN,NaN,2.230296e+10,NaN,1377.358491
10,Afghanistan,30552000.0,2549,Légumineuses Autres,Vegetaux,4.0,NaN,23.0,2.44,0.14,...,26.0,74.0,3.0,60.0,5.0,NaN,NaN,2.564840e+11,1.739631e+07,3440.573770
11,Afghanistan,30552000.0,2551,Noix,Vegetaux,NaN,NaN,12.0,1.45,1.07,...,NaN,44.0,NaN,56.0,NaN,NaN,NaN,1.338178e+11,4.237562e+06,3020.689655
12,Afghanistan,30552000.0,2557,Graines de tournesol,Vegetaux,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.0,0.0,3.0,NaN,NaN,NaN,NaN
13,Afghanistan,30552000.0,2559,Graines de coton,Vegetaux,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,27.0,1.0,26.0,NaN,NaN,NaN,NaN
15,Afghanistan,30552000.0,2561,Sésame,Vegetaux,NaN,NaN,9.0,0.52,0.77,...,NaN,16.0,1.0,32.0,1.0,4.0,0.0,1.003633e+11,3.010900e+06,6317.307692
16,Afghanistan,30552000.0,2563,Olives,Vegetaux,NaN,NaN,0.0,0.06,0.03,...,NaN,2.0,0.0,7.0,NaN,4.0,NaN,0.000000e+00,0.000000e+00,0.000000
17,Afghanistan,30552000.0,2570,"Plantes Oleiferes, Autre",Vegetaux,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,3.0,0.0,2.0,NaN,NaN,NaN,NaN
18,Afghanistan,30552000.0,2571,Huile de Soja,Vegetaux,NaN,NaN,13.0,0.53,1.46,...,16.0,16.0,NaN,NaN,NaN,NaN,NaN,1.449692e+11,NaN,8952.830189
20,Afghanistan,30552000.0,2573,Huile de Tournesol,Vegetaux,NaN,NaN,18.0,0.75,2.06,...,22.0,23.0,NaN,1.0,NaN,NaN,NaN,2.007266e+11,NaN,8760.000000
21,Afghanistan,30552000.0,2574,Huile de Colza&Moutarde,Vegetaux,NaN,NaN,2.0,0.07,0.18,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,2.230296e+10,NaN,10428.571429
22,Afghanistan,30552000.0,2575,Huile Graines de Coton,Vegetaux,NaN,1.0,3.0,0.12,0.34,...,NaN,4.0,NaN,5.0,NaN,NaN,NaN,3.345444e+10,NaN,9125.000000
23,Afghanistan,30552000.0,2577,Huile de Palme,Vegetaux,NaN,55.0,51.0,2.09,5.74,...,119.0,64.0,NaN,NaN,NaN,NaN,NaN,5.687255e+11,NaN,8906.698565
24,Afghanistan,30552000.0,2579,Huile de Sésame,Vegetaux,NaN,NaN,1.0,0.05,0.13,...,NaN,1.0,NaN,1.0,NaN,NaN,NaN,1.115148e+10,NaN,7300.000000
25,Afghanistan,30552000.0,2580,Huile d'Olive,Vegetaux,NaN,NaN,0.0,0.02,0.05,...,0.0,1.0,NaN,1.0,NaN,NaN,NaN,0.000000e+00,NaN,0.000000
26,Afghanistan,30552000.0,2586,Huil Plantes Oleif Autr,Vegetaux,NaN,359.0,2.0,0.08,0.21,...,360.0,2.0,NaN,1.0,NaN,NaN,NaN,2.230296e+10,0.000000e+00,9125.000000
28,Afghanistan,30552000.0,2605,"Légumes, Autres",Vegetaux,NaN,NaN,17.0,28.97,0.13,...,124.0,885.0,122.0,916.0,NaN,NaN,NaN,1.895752e+11,9.478758e+06,214.187090
29,Afghanistan,30552000.0,2611,"Oranges, Mandarines",Vegetaux,NaN,NaN,4.0,4.75,0.01,...,139.0,145.0,0.0,6.0,NaN,NaN,NaN,4.460592e+10,7.806036e+05,307.368421
30,Afghanistan,30552000.0,2614,"Agrumes, Autres",Vegetaux,NaN,NaN,1.0,1.29,0.01,...,40.0,39.0,2.0,3.0,NaN,NaN,NaN,1.115148e+10,2.230296e+05,282.945736
31,Afghanistan,30552000.0,2615,Bananes,Vegetaux,NaN,NaN,4.0,2.70,0.02,...,82.0,82.0,NaN,NaN,NaN,NaN,NaN,4.460592e+10,5.575740e+05,540.740741
32,Afghanistan,30552000.0,2617,Pommes,Vegetaux,NaN,NaN,3.0,2.22,0.01,...,0.0,68.0,4.0,79.0,NaN,NaN,NaN,3.345444e+10,2.230296e+05,493.243243
34,Afghanistan,30552000.0,2619,Dattes,Vegetaux,NaN,NaN,0.0,0.02,0.00,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15457,Îles Salomon,561000.0,2618,Ananas,Vegetaux,NaN,NaN,0.0,0.01,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,0.000000
15458,Îles Salomon,561000.0,2620,Raisin,Vegetaux,NaN,NaN,0.0,0.04,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,0.000000
15459,Îles Salomon,561000.0,2625,"Fruits, Autres",Vegetaux,NaN,NaN,59.0,49.35,0.63,...,2.0,28.0,1.0,27.0,NaN,NaN,NaN,1.208114e+10,1.330972e+05,436.372847
15460,Îles Salomon,561000.0,2630,Café,Vegetaux,NaN,NaN,1.0,1.05,NaN,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.047650e+08,3.890535e+04,347.619048
15461,Îles Salomon,561000.0,2633,Feve de Cacao,Vegetaux,NaN,NaN,4.0,0.41,0.42,...,0.0,0.0,NaN,5.0,NaN,NaN,-1.0,8.190600e+08,1.023825e+04,3560.975610
15462,Îles Salomon,561000.0,2635,Thé,Vegetaux,NaN,NaN,0.0,0.17,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,8.190600e+03,0.000000
15464,Îles Salomon,561000.0,2645,"Épices, Autres",Vegetaux,NaN,NaN,4.0,0.48,0.21,...,0.0,0.0,NaN,0.0,NaN,NaN,NaN,8.190600e+08,3.071475e+04,3041.666667
15465,Îles Salomon,561000.0,2655,Vin,Vegetaux,NaN,NaN,0.0,0.07,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,0.000000
15466,Îles Salomon,561000.0,2656,Bière,Vegetaux,NaN,NaN,8.0,6.55,NaN,...,0.0,4.0,NaN,4.0,NaN,NaN,NaN,1.638120e+09,1.842885e+04,445.801527
15468,Îles Salomon,561000.0,2658,Boissons Alcooliques,Vegetaux,NaN,NaN,0.0,0.03,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.000000e+00,NaN,0.000000
15469,Îles Salomon,561000.0,2659,"Alcool, non Comestible",Vegetaux,NaN,0.0,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15470,Îles Salomon,561000.0,2680,Aliments pour enfants,Vegetaux,NaN,NaN,0.0,0.03,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,2.047650e+03,0.000000
15471,Îles Salomon,561000.0,2731,Viande de Bovins,Animaux,NaN,NaN,27.0,5.57,1.80,...,2.0,3.0,NaN,1.0,NaN,NaN,NaN,5.528655e+09,5.364843e+05,1769.299820
15472,Îles Salomon,561000.0,2732,Viande d'Ovins/Caprins,Animaux,NaN,NaN,1.0,0.14,0.09,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,2.047650e+08,1.023825e+04,2607.142857
15473,Îles Salomon,561000.0,2733,Viande de Suides,Animaux,NaN,NaN,45.0,4.70,4.28,...,0.0,3.0,NaN,2.0,NaN,NaN,NaN,9.214425e+09,2.887187e+05,3494.680851
15474,Îles Salomon,561000.0,2734,Viande de Volailles,Animaux,NaN,NaN,11.0,3.34,0.69,...,2.0,2.0,NaN,0.0,NaN,NaN,NaN,2.252415e+09,2.334321e+05,1202.095808
15475,Îles Salomon,561000.0,2735,"Viande, Autre",Animaux,NaN,NaN,0.0,0.06,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,8.190600e+03,0.000000
15476,Îles Salomon,561000.0,2736,Abats Comestible,Animaux,NaN,NaN,2.0,0.64,0.05,...,0.0,0.0,NaN,0.0,NaN,NaN,NaN,4.095300e+08,6.552480e+04,1140.625000
15477,Îles Salomon,561000.0,2737,Graisses Animales Crue,Animaux,NaN,0.0,17.0,0.88,1.89,...,0.0,0.0,NaN,0.0,NaN,NaN,NaN,3.481005e+09,1.842885e+04,7051.136364
15478,Îles Salomon,561000.0,2740,"Beurre, Ghee",Animaux,NaN,NaN,1.0,0.07,0.17,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,2.047650e+08,NaN,5214.285714
15479,Îles Salomon,561000.0,2743,Crème,Animaux,NaN,NaN,0.0,0.02,0.01,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000
15480,Îles Salomon,561000.0,2744,Oeufs,Animaux,NaN,NaN,5.0,1.28,0.36,...,0.0,1.0,0.0,1.0,0.0,NaN,NaN,1.023825e+09,8.190600e+04,1425.781250
15482,Îles Salomon,561000.0,2762,Perciform,Animaux,NaN,0.0,0.0,0.02,0.00,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000
15483,Îles Salomon,561000.0,2763,Poissons Pelagiques,Animaux,NaN,0.0,32.0,13.60,1.34,...,0.0,8.0,NaN,25.0,NaN,NaN,0.0,6.552480e+09,9.603479e+05,858.823529
15484,Îles Salomon,561000.0,2764,"Poissons Marins, Autres",Animaux,NaN,0.0,36.0,19.01,1.33,...,2.0,11.0,NaN,10.0,NaN,NaN,0.0,7.371540e+09,1.140541e+06,691.215150
15485,Îles Salomon,561000.0,2765,Crustacés,Animaux,NaN,0.0,0.0,0.03,0.00,...,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.000000e+00,2.047650e+03,0.000000
15487,Îles Salomon,561000.0,2767,"Mollusques, Autres",Animaux,NaN,0.0,0.0,0.95,0.01,...,1.0,1.0,NaN,0.0,NaN,NaN,NaN,0.000000e+00,1.228590e+04,0.000000
15492,Îles Salomon,561000.0,2805,Riz (Eq Blanchi),Vegetaux,0.0,12.0,623.0,63.76,1.36,...,47.0,36.0,1.0,3.0,0.0,NaN,0.0,1.275686e+11,2.231938e+06,3566.420954
15493,Îles Salomon,561000.0,2848,Lait - Excl Beurre,Animaux,0.0,NaN,19.0,11.52,0.70,...,5.0,6.0,0.0,1.0,NaN,NaN,NaN,3.890535e+09,2.150033e+05,601.996528
15494,Îles Salomon,561000.0,2899,Miscellanees,Vegetaux,NaN,NaN,3.0,NaN,0.04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.142950e+08,2.047650e+04,NaN

#### Ratio énergie/poids de l'oeuf
147 kcal pour 100g, soit 1470 kcal/kg, ce qui semble assez cohérent avec les différents ratios énergie/poids des oeufs observés dans le monde:

In [21]:
ratio_oeuf = dispo_alim.loc[dispo_alim.Produit == 'Oeufs']
ratio_oeuf[['Ratio Energie-Poids (kcal/kg)']]

Élément  Ratio Energie-Poids (kcal/kg)
54                         1403.846154
139                        1417.475728
231                        1348.594378
324                        1222.704715
419                        1406.147541
500                        1315.315315
591                        1264.434180
684                        1427.374302
777                        1313.871817
867                        1405.047049
962                        1372.502938
1031                       1417.234332
1123                       1378.197320
1212                       1354.032258
1306                       1579.326923
1399                       1291.363163
1493                       1420.571882
1583                       1279.381443
1664                       1394.436997
1756                       1268.339768
1847                       1381.959911
1941                       1310.256410
2036                       1468.131188
2132                       1341.314031
2225                       1397.129187
2315                       1258.620690
2404                       1403.846154
2495                       1216.666667
2578                       1221.456693
2667                       1332.116788
...                                ...
12945                      1474.747475
13033                      1437.636761
13128                      1386.514720
13216                      1300.254453
13307                      1446.896036
13401                      1343.558282
13470                      1280.701754
13541                      1520.833333
13633                      1377.358491
13728                      1536.842105
13791                      1557.926829
13880                      1273.255814
13971                      1303.571429
14062                      1237.288136
14121                      1389.593909
14212                      1468.902439
14303                      1398.389783
14396                      1305.555556
14480                      1412.202381
14575                      1296.625222
14656                      1425.781250
14749                      1473.094170
14842                      1209.337349
14934                      1251.428571
15027                      1431.372549
15119                      1374.848117
15214                      1321.473159
15309                      1401.920439
15402                      1013.888889
15480                      1425.781250

[170 rows x 1 columns]

#### Pourcentage de protéines contenu par chaque produit dans chaque pays

In [22]:
# Ajout de la colonne totalisant ce ratio
dispo_alim['Ratio Protéines-Poids (%)'] = (dispo_alim.loc[:, 'Disponibilité de protéines en quantité (g/personne/jour)'] * 365)  / (dispo_alim.loc[:, 'Disponibilité alimentaire en quantité (kg/personne/an)'] * 1000) * 100
dispo_alim

Élément,Zone,Population,Code Produit,Produit,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,Disponibilité alimentaire annuelle en Kcal,Disponibilité de protéines annuelle en Kg,Ratio Energie-Poids (kcal/kg),Ratio Protéines-Poids (%)
0,Afghanistan,30552000.0,2511,Blé,Vegetaux,NaN,NaN,1369.0,160.23,4.69,...,4895.0,775.0,5169.0,322.0,NaN,-350.0,1.526638e+13,4.116011e+08,3118.548337,8.408007
1,Afghanistan,30552000.0,2513,Orge,Vegetaux,360.0,NaN,26.0,2.92,0.24,...,89.0,52.0,514.0,22.0,NaN,0.0,2.899385e+11,8.809669e+06,3250.000000,9.875000
2,Afghanistan,30552000.0,2514,Maïs,Vegetaux,200.0,NaN,21.0,2.50,0.30,...,76.0,31.0,312.0,5.0,NaN,NaN,2.341811e+11,6.244829e+06,3066.000000,8.176000
3,Afghanistan,30552000.0,2517,Millet,Vegetaux,NaN,NaN,3.0,0.40,0.02,...,12.0,1.0,13.0,0.0,NaN,NaN,3.345444e+10,8.921184e+05,2737.500000,7.300000
5,Afghanistan,30552000.0,2531,Pommes de Terre,Vegetaux,NaN,NaN,15.0,7.53,0.04,...,230.0,9.0,303.0,23.0,NaN,NaN,1.672722e+11,2.787870e+06,727.091633,1.211819
6,Afghanistan,30552000.0,2536,"Sucre, canne",Vegetaux,81.0,NaN,NaN,NaN,NaN,...,NaN,NaN,90.0,NaN,9.0,NaN,NaN,NaN,NaN,NaN
7,Afghanistan,30552000.0,2537,"Sucre, betterave",Vegetaux,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,15.0,NaN,15.0,NaN,NaN,NaN,NaN,NaN
8,Afghanistan,30552000.0,2542,Sucre Eq Brut,Vegetaux,NaN,NaN,84.0,8.35,NaN,...,255.0,NaN,2.0,NaN,NaN,-19.0,9.367243e+11,NaN,3671.856287,NaN
9,Afghanistan,30552000.0,2543,Edulcorants Autres,Vegetaux,NaN,NaN,2.0,0.53,NaN,...,16.0,NaN,NaN,NaN,NaN,NaN,2.230296e+10,NaN,1377.358491,NaN
10,Afghanistan,30552000.0,2549,Légumineuses Autres,Vegetaux,4.0,NaN,23.0,2.44,0.14,...,74.0,3.0,60.0,5.0,NaN,NaN,2.564840e+11,1.739631e+07,3440.573770,23.336066
11,Afghanistan,30552000.0,2551,Noix,Vegetaux,NaN,NaN,12.0,1.45,1.07,...,44.0,NaN,56.0,NaN,NaN,NaN,1.338178e+11,4.237562e+06,3020.689655,9.565517
12,Afghanistan,30552000.0,2557,Graines de tournesol,Vegetaux,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN
13,Afghanistan,30552000.0,2559,Graines de coton,Vegetaux,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.0,1.0,26.0,NaN,NaN,NaN,NaN,NaN
15,Afghanistan,30552000.0,2561,Sésame,Vegetaux,NaN,NaN,9.0,0.52,0.77,...,16.0,1.0,32.0,1.0,4.0,0.0,1.003633e+11,3.010900e+06,6317.307692,18.951923
16,Afghanistan,30552000.0,2563,Olives,Vegetaux,NaN,NaN,0.0,0.06,0.03,...,2.0,0.0,7.0,NaN,4.0,NaN,0.000000e+00,0.000000e+00,0.000000,0.000000
17,Afghanistan,30552000.0,2570,"Plantes Oleiferes, Autre",Vegetaux,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,3.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN
18,Afghanistan,30552000.0,2571,Huile de Soja,Vegetaux,NaN,NaN,13.0,0.53,1.46,...,16.0,NaN,NaN,NaN,NaN,NaN,1.449692e+11,NaN,8952.830189,NaN
20,Afghanistan,30552000.0,2573,Huile de Tournesol,Vegetaux,NaN,NaN,18.0,0.75,2.06,...,23.0,NaN,1.0,NaN,NaN,NaN,2.007266e+11,NaN,8760.000000,NaN
21,Afghanistan,30552000.0,2574,Huile de Colza&Moutarde,Vegetaux,NaN,NaN,2.0,0.07,0.18,...,2.0,NaN,NaN,NaN,NaN,NaN,2.230296e+10,NaN,10428.571429,NaN
22,Afghanistan,30552000.0,2575,Huile Graines de Coton,Vegetaux,NaN,1.0,3.0,0.12,0.34,...,4.0,NaN,5.0,NaN,NaN,NaN,3.345444e+10,NaN,9125.000000,NaN
23,Afghanistan,30552000.0,2577,Huile de Palme,Vegetaux,NaN,55.0,51.0,2.09,5.74,...,64.0,NaN,NaN,NaN,NaN,NaN,5.687255e+11,NaN,8906.698565,NaN
24,Afghanistan,30552000.0,2579,Huile de Sésame,Vegetaux,NaN,NaN,1.0,0.05,0.13,...,1.0,NaN,1.0,NaN,NaN,NaN,1.115148e+10,NaN,7300.000000,NaN
25,Afghanistan,30552000.0,2580,Huile d'Olive,Vegetaux,NaN,NaN,0.0,0.02,0.05,...,1.0,NaN,1.0,NaN,NaN,NaN,0.000000e+00,NaN,0.000000,NaN
26,Afghanistan,30552000.0,2586,Huil Plantes Oleif Autr,Vegetaux,NaN,359.0,2.0,0.08,0.21,...,2.0,NaN,1.0,NaN,NaN,NaN,2.230296e+10,0.000000e+00,9125.000000,0.000000
28,Afghanistan,30552000.0,2605,"Légumes, Autres",Vegetaux,NaN,NaN,17.0,28.97,0.13,...,885.0,122.0,916.0,NaN,NaN,NaN,1.895752e+11,9.478758e+06,214.187090,1.070935
29,Afghanistan,30552000.0,2611,"Oranges, Mandarines",Vegetaux,NaN,NaN,4.0,4.75,0.01,...,145.0,0.0,6.0,NaN,NaN,NaN,4.460592e+10,7.806036e+05,307.368421,0.537895
30,Afghanistan,30552000.0,2614,"Agrumes, Autres",Vegetaux,NaN,NaN,1.0,1.29,0.01,...,39.0,2.0,3.0,NaN,NaN,NaN,1.115148e+10,2.230296e+05,282.945736,0.565891
31,Afghanistan,30552000.0,2615,Bananes,Vegetaux,NaN,NaN,4.0,2.70,0.02,...,82.0,NaN,NaN,NaN,NaN,NaN,4.460592e+10,5.575740e+05,540.740741,0.675926
32,Afghanistan,30552000.0,2617,Pommes,Vegetaux,NaN,NaN,3.0,2.22,0.01,...,68.0,4.0,79.0,NaN,NaN,NaN,3.345444e+10,2.230296e+05,493.243243,0.328829
34,Afghanistan,30552000.0,2619,Dattes,Vegetaux,NaN,NaN,0.0,0.02,0.00,...,1.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15457,Îles Salomon,561000.0,2618,Ananas,Vegetaux,NaN,NaN,0.0,0.01,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,0.000000,NaN
15458,Îles Salomon,561000.0,2620,Raisin,Vegetaux,NaN,NaN,0.0,0.04,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,0.000000,NaN
15459,Îles Salomon,561000.0,2625,"Fruits, Autres",Vegetaux,NaN,NaN,59.0,49.35,0.63,...,28.0,1.0,27.0,NaN,NaN,NaN,1.208114e+10,1.330972e+05,436.372847,0.480750
15460,Îles Salomon,561000.0,2630,Café,Vegetaux,NaN,NaN,1.0,1.05,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,2.047650e+08,3.890535e+04,347.619048,6.604762
15461,Îles Salomon,561000.0,2633,Feve de Cacao,Vegetaux,NaN,NaN,4.0,0.41,0.42,...,0.0,NaN,5.0,NaN,NaN,-1.0,8.190600e+08,1.023825e+04,3560.975610,4.451220
15462,Îles Salomon,561000.0,2635,Thé,Vegetaux,NaN,NaN,0.0,0.17,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,8.190600e+03,0.000000,8.588235
15464,Îles Salomon,561000.0,2645,"Épices, Autres",Vegetaux,NaN,NaN,4.0,0.48,0.21,...,0.0,NaN,0.0,NaN,NaN,NaN,8.190600e+08,3.071475e+04,3041.666667,11.406250
15465,Îles Salomon,561000.0,2655,Vin,Vegetaux,NaN,NaN,0.0,0.07,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,0.000000,NaN
15466,Îles Salomon,561000.0,2656,Bière,Vegetaux,NaN,NaN,8.0,6.55,NaN,...,4.0,NaN,4.0,NaN,NaN,NaN,1.638120e+09,1.842885e+04,445.801527,0.501527
15468,Îles Salomon,561000.0,2658,Boissons Alcooliques,Vegetaux,NaN,NaN,0.0,0.03,NaN,...,0.0,NaN,NaN,NaN,NaN,0.0,0.000000e+00,NaN,0.000000,NaN
15469,Îles Salomon,561000.0,2659,"Alcool, non Comestible",Vegetaux,NaN,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15470,Îles Salomon,561000.0,2680,Aliments pour enfants,Vegetaux,NaN,NaN,0.0,0.03,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,2.047650e+03,0.000000,12.166667
15471,Îles Salomon,561000.0,2731,Viande de Bovins,Animaux,NaN,NaN,27.0,5.57,1.80,...,3.0,NaN,1.0,NaN,NaN,NaN,5.528655e+09,5.364843e+05,1769.299820,17.168761
15472,Îles Salomon,561000.0,2732,Viande d'Ovins/Caprins,Animaux,NaN,NaN,1.0,0.14,0.09,...,0.0,NaN,NaN,NaN,NaN,NaN,2.047650e+08,1.023825e+04,2607.142857,13.035714
15473,Îles Salomon,561000.0,2733,Viande de Suides,Animaux,NaN,NaN,45.0,4.70,4.28,...,3.0,NaN,2.0,NaN,NaN,NaN,9.214425e+09,2.887187e+05,3494.680851,10.950000
15474,Îles Salomon,561000.0,2734,Viande de Volailles,Animaux,NaN,NaN,11.0,3.34,0.69,...,2.0,NaN,0.0,NaN,NaN,NaN,2.252415e+09,2.334321e+05,1202.095808,12.458084
15475,Îles Salomon,561000.0,2735,"Viande, Autre",Animaux,NaN,NaN,0.0,0.06,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,8.190600e+03,0.000000,24.333333
15476,Îles Salomon,561000.0,2736,Abats Comestible,Animaux,NaN,NaN,2.0,0.64,0.05,...,0.0,NaN,0.0,NaN,NaN,NaN,4.095300e+08,6.552480e+04,1140.625000,18.250000
15477,Îles Salomon,561000.0,2737,Graisses Animales Crue,Animaux,NaN,0.0,17.0,0.88,1.89,...,0.0,NaN,0.0,NaN,NaN,NaN,3.481005e+09,1.842885e+04,7051.136364,3.732955
15478,Îles Salomon,561000.0,2740,"Beurre, Ghee",Animaux,NaN,NaN,1.0,0.07,0.17,...,0.0,NaN,NaN,NaN,NaN,NaN,2.047650e+08,NaN,5214.285714,NaN
15479,Îles Salomon,561000.0,2743,Crème,Animaux,NaN,NaN,0.0,0.02,0.01,...,0.0,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000,0.000000
15480,Îles Salomon,561000.0,2744,Oeufs,Animaux,NaN,NaN,5.0,1.28,0.36,...,1.0,0.0,1.0,0.0,NaN,NaN,1.023825e+09,8.190600e+04,1425.781250,11.406250
15482,Îles Salomon,561000.0,2762,Perciform,Animaux,NaN,0.0,0.0,0.02,0.00,...,0.0,NaN,0.0,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000,0.000000
15483,Îles Salomon,561000.0,2763,Poissons Pelagiques,Animaux,NaN,0.0,32.0,13.60,1.34,...,8.0,NaN,25.0,NaN,NaN,0.0,6.552480e+09,9.603479e+05,858.823529,12.587132
15484,Îles Salomon,561000.0,2764,"Poissons Marins, Autres",Animaux,NaN,0.0,36.0,19.01,1.33,...,11.0,NaN,10.0,NaN,NaN,0.0,7.371540e+09,1.140541e+06,691.215150,10.694634
15485,Îles Salomon,561000.0,2765,Crustacés,Animaux,NaN,0.0,0.0,0.03,0.00,...,0.0,NaN,0.0,NaN,NaN,NaN,0.000000e+00,2.047650e+03,0.000000,12.166667
15487,Îles Salomon,561000.0,2767,"Mollusques, Autres",Animaux,NaN,0.0,0.0,0.95,0.01,...,1.0,NaN,0.0,NaN,NaN,NaN,0.000000e+00,1.228590e+04,0.000000,2.305263
15492,Îles Salomon,561000.0,2805,Riz (Eq Blanchi),Vegetaux,0.0,12.0,623.0,63.76,1.36,...,36.0,1.0,3.0,0.0,NaN,0.0,1.275686e+11,2.231938e+06,3566.420954,6.239806
15493,Îles Salomon,561000.0,2848,Lait - Excl Beurre,Animaux,0.0,NaN,19.0,11.52,0.70,...,6.0,0.0,1.0,NaN,NaN,NaN,3.890535e+09,2.150033e+05,601.996528,3.326823
15494,Îles Salomon,561000.0,2899,Miscellanees,Vegetaux,NaN,NaN,3.0,NaN,0.04,...,NaN,NaN,NaN,NaN,NaN,NaN,6.142950e+08,2.047650e+04,NaN,NaN

#### Pourcentage de protéines dans l'avoine:
10,70g pour 100g, soit 10,7%, ce qui présente encore une cohérence avec les données de la (dernière) colonne 'Ratio Protéines-Poids (%)':

In [23]:
ratio_avoine = dispo_alim.loc[dispo_alim.Produit == 'Avoine']
ratio_avoine[['Ratio Protéines-Poids (%)']].loc[(ratio_avoine['Ratio Protéines-Poids (%)'].notnull()) & (ratio_avoine['Ratio Protéines-Poids (%)'] > 0.1)]

Élément  Ratio Protéines-Poids (%)
64                        7.786667
159                       8.423077
344                      11.376623
519                       8.749064
610                       9.419355
704                       8.554688
797                       8.878378
887                       8.588235
982                      11.243304
1051                      7.821429
1142                      8.700581
1326                      8.774038
1418                      9.125000
1512                      9.022472
1683                      7.215116
1776                      8.111111
1867                      8.423077
1961                      7.647619
2056                      7.366972
2152                      8.241935
2333                      8.794152
2514                      6.083333
2781                     10.500000
2877                      8.828520
2970                      7.357708
3066                     11.060606
3157                      8.657051
3251                      9.125000
3347                      8.716418
3441                      8.690476
...                            ...
10598                     8.111111
10690                    10.024648
10785                     8.588235
10880                     7.786667
11061                     8.295455
11251                     8.690476
11344                     8.766616
11708                     8.902439
11796                    12.166667
11952                     6.989362
12109                     8.552805
12192                     8.295455
12278                     8.844231
12513                     9.733333
12605                     9.125000
12688                    10.114458
12781                    10.428571
12958                    18.250000
13053                     5.087879
13147                     8.566327
13233                     9.591241
13559                     7.144681
14232                     8.776404
14323                     7.300000
14499                     7.180328
14675                     7.300000
14768                    12.166667
15139                     9.618243
15234                     7.300000
15329                    11.368852

[117 rows x 1 columns]

<a class='anchor' id='Question5'></a>
## Question 5: Citez 5 aliments parmi les 20 plus caloriques grâce au ratio énergie/poids

#### Aliments les plus riches en calories

In [24]:
# Calcul de la moyenne du ratio pour chaque produit
ratio_cal_produit = dispo_alim.groupby('Produit').mean()
ratio_cal_produit[['Ratio Energie-Poids (kcal/kg)']]

Élément                   Ratio Energie-Poids (kcal/kg)
Produit
Abats Comestible                            1125.729057
Agrumes, Autres                               75.577220
Alcool, non Comestible                              NaN
Aliments pour enfants                       3050.469022
Ananas                                       336.586837
Animaux Aquatiques Autre                      65.569218
Arachides Decortiquees                      5466.324644
Avoine                                      1794.922084
Bananes                                      587.194203
Bananes plantains                            679.060198
Beurre, Ghee                                6981.558208
Bière                                        440.058130
Blé                                         2851.016900
Boissons Alcooliques                        2679.713130
Boissons Fermentés                           261.703543
Café                                         358.959446
Cephalopodes                                 389.251375
Citrons & Limes                              123.704018
Coco (Incl Coprah)                          1122.877631
Crustacés                                    316.647301
Crème                                       1168.231743
Céréales, Autres                            2408.266953
Dattes                                      1081.002063
Edulcorants Autres                          2407.427208
Feve de Cacao                               4343.034036
Fruits, Autres                               436.275322
Girofles                                     483.301603
Graines Colza/Moutarde                      3175.500000
Graines de coton                                    NaN
Graines de tournesol                        2275.041822
...                                                 ...
Piments                                     2514.499721
Plantes Aquatiques                           367.682865
Plantes Oleiferes, Autre                    2631.827466
Pois                                        3106.951940
Poissons Eau Douce                           596.610765
Poissons Marins, Autres                      596.502970
Poissons Pelagiques                          886.824833
Poivre                                      1722.609054
Pommes                                       335.799141
Pommes de Terre                              650.830925
Racines nda                                  697.729055
Raisin                                       472.927019
Riz (Eq Blanchi)                            3640.609092
Seigle                                      2040.545031
Soja                                        1748.819646
Sorgho                                      2976.920814
Sucre Eq Brut                               3578.891980
Sucre non centrifugé                        3254.135701
Sucre, betterave                             340.342984
Sucre, canne                                 229.953377
Sésame                                      5010.932143
Thé                                          188.700550
Tomates                                      189.402301
Viande d'Ovins/Caprins                      1931.764583
Viande de Bovins                            1689.974636
Viande de Suides                            2363.791958
Viande de Volailles                         1302.257106
Viande, Autre                               1086.640740
Vin                                          573.146636
Épices, Autres                              3106.064527

[97 rows x 1 columns]

In [25]:
# Sélection des 20 produits ayant le plus haut ratio énergie/poids:
vingt_produits_caloriques = ratio_cal_produit.nlargest(20, 'Ratio Energie-Poids (kcal/kg)')[['Ratio Energie-Poids (kcal/kg)']]
vingt_produits_caloriques

Élément                  Ratio Energie-Poids (kcal/kg)
Produit
Huile de Palme                             8785.558639
Huile de Soja                              8623.341919
Huile de Son de Riz                        8497.969939
Huile de Colza&Moutarde                    8363.006477
Huile de Tournesol                         8300.429002
Huil Plantes Oleif Autr                    8233.678296
Huile Graines de Coton                     8177.340910
Huile de Coco                              8088.061463
Huile de Palmistes                         7885.602997
Huile de Germe de Maïs                     7816.529184
Huile d'Arachide                           7808.499728
Huile d'Olive                              7767.356167
Graisses Animales Crue                     7578.657377
Huile de Sésame                            7577.440831
Huiles de Poissons                         7133.945055
Beurre, Ghee                               6981.558208
Palmistes                                  5475.000000
Arachides Decortiquees                     5466.324644
Sésame                                     5010.932143
Feve de Cacao                              4343.034036

#### 5 aliments parmi les 20 aliments les plus caloriques:
- Huile de Palme
- Huile de Tournesol
- Huile de Coco
- Beurre, Ghee
- Fève de Cacao

#### Aliments les plus riches en protéines

In [26]:
# Sélection des 20 produits ayant le plus haut ratio protéines/poids:
produits_protéinés = ratio_cal_produit.nlargest(20, 'Ratio Protéines-Poids (%)')[['Ratio Protéines-Poids (%)']]
produits_protéinés

Élément                   Ratio Protéines-Poids (%)
Produit
Soja                                      25.338211
Arachides Decortiquees                    24.790816
Pois                                      22.108112
Légumineuses Autres                       22.025876
Haricots                                  21.719055
Sésame                                    17.828134
Abats Comestible                          17.618325
Viande, Autre                             17.411869
Plantes Oleiferes, Autre                  16.671572
Aliments pour enfants                     14.872622
Viande de Bovins                          14.470612
Cephalopodes                              14.155817
Viande d'Ovins/Caprins                    13.734867
Viande de Volailles                       12.617369
Poissons Pelagiques                       12.116990
Piments                                   11.337096
Poissons Marins, Autres                   11.033518
Graines Colza/Moutarde                    10.950000
Épices, Autres                            10.744898
Oeufs                                     10.697798

#### 5 aliments parmi les 20 aliments les plus riches en protéines:
- Soja
- Pois
- Abats Comestibles
- Viandes de Volailles
- Piments

<a class='anchor' id='Question6'></a>
## Question 6: Calculez la disponibilité intérieure mondiale en kcal pour tous les produits végétaux

In [27]:
dispo_alim_veg = dispo_alim.loc[dispo_alim.Origine == 'Vegetaux']

# Ajout d'une colonne précisant la disponibilité intérieure en Kcal des produits végétaux dans chaque pays:
dispo_alim_veg['Disponibilité intérieure en Kcal'] = dispo_alim_veg.loc[:, 'Disponibilité intérieure'] * 1e6 * dispo_alim_veg.loc[:, 'Ratio Energie-Poids (kcal/kg)']
dispo_alim_veg.head()

Élément,Zone,Population,Code Produit,Produit,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Pertes,Production,Semences,Traitement,Variation de stock,Disponibilité alimentaire annuelle en Kcal,Disponibilité de protéines annuelle en Kg,Ratio Energie-Poids (kcal/kg),Ratio Protéines-Poids (%),Disponibilité intérieure en Kcal
0,Afghanistan,30552000.0,2511,Blé,Vegetaux,NaN,NaN,1369.0,160.23,4.69,...,775.0,5169.0,322.0,NaN,-350.0,1.526638e+13,411601126.8,3118.548337,8.408007,1.868634e+13
1,Afghanistan,30552000.0,2513,Orge,Vegetaux,360.0,NaN,26.0,2.92,0.24,...,52.0,514.0,22.0,NaN,0.0,2.899385e+11,8809669.2,3250.000000,9.875000,1.703000e+12
2,Afghanistan,30552000.0,2514,Maïs,Vegetaux,200.0,NaN,21.0,2.50,0.30,...,31.0,312.0,5.0,NaN,NaN,2.341811e+11,6244828.8,3066.000000,8.176000,9.596580e+11
3,Afghanistan,30552000.0,2517,Millet,Vegetaux,NaN,NaN,3.0,0.40,0.02,...,1.0,13.0,0.0,NaN,NaN,3.345444e+10,892118.4,2737.500000,7.300000,3.558750e+10
5,Afghanistan,30552000.0,2531,Pommes de Terre,Vegetaux,NaN,NaN,15.0,7.53,0.04,...,9.0,303.0,23.0,NaN,NaN,1.672722e+11,2787870.0,727.091633,1.211819,1.904980e+11

#### Somme de la disponibilité intérieure végétale mondiale en Kcal:

In [28]:
# Somme de la disponibilité intérieure en Kcal des produits végétaux dans le monde
dispo_inter_veg_mondiale_kcal = dispo_alim_veg['Disponibilité intérieure en Kcal'].sum()
print(dispo_inter_veg_mondiale_kcal)

1.216126195482513e+16

<a class='anchor' id='Question7'></a>
## Question 7: Nombre d'humains pouvant être nourris par la quantité de produits végétaux disponibles

#### - Selon les besoins caloriques annuels d'un individu

Selon la FAO, le besoin énergétique alimentaire minimum d'un humain d'âge moyen est de 1680 kcal/personne/jour*. Pour donner un peu de souplesse à notre indicateur, nous allons retenir un niveau de 2000 kcal/personne/jour, soit 730 000 kcal par personne/an.

*source: Méthodologie de la FAO pour mesurer la prévalence de la sous-alimentation, http://www.fao.org/fileadmin/templates/ess/documents/food_security_statistics/metadata/methologie_sousalimentation.pdf

In [29]:
# Besoin énergétique annuel d'un humain d'âge moyen
besoin_energ_min = 730000

# Population à laquelle la disponibilité intérieure pourrait potentiellement répondre aux besoins énergétiques
pop_nourrie_dispo_inter_veg_mondiale_kcal = dispo_inter_veg_mondiale_kcal / besoin_energ_min
print(pop_nourrie_dispo_inter_veg_mondiale_kcal)

16659262951.815247

In [30]:
pourcent_pop_nourrie_dispo_inter_veg_mondiale_kcal = pop_nourrie_dispo_inter_veg_mondiale_kcal / population_mondiale * 100
print(pourcent_pop_nourrie_dispo_inter_veg_mondiale_kcal)

238.08041745968742

La production annuelle de produits végétaux pourrait répondre aux besoins caloriques de 16 659 262 951 humains si cette production était dédiée uniquement à l'alimentation, soit 238,1 % de la population mondiale.

#### - Selon les besoins annuels en protéines de la population mondiale

In [31]:
# Calcul de la disponibilité intérieure en protéines des produits végétaux dans chaque pays (en gr.):
dispo_alim_veg['Disponibilité intérieure en protéines (gr.)'] = (dispo_alim_veg.loc[:, 'Disponibilité intérieure'] * 1e9) * (dispo_alim_veg.loc[:, 'Ratio Protéines-Poids (%)'] / 100)
dispo_alim_veg.head()

Élément,Zone,Population,Code Produit,Produit,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Production,Semences,Traitement,Variation de stock,Disponibilité alimentaire annuelle en Kcal,Disponibilité de protéines annuelle en Kg,Ratio Energie-Poids (kcal/kg),Ratio Protéines-Poids (%),Disponibilité intérieure en Kcal,Disponibilité intérieure en protéines (gr.)
0,Afghanistan,30552000.0,2511,Blé,Vegetaux,NaN,NaN,1369.0,160.23,4.69,...,5169.0,322.0,NaN,-350.0,1.526638e+13,411601126.8,3118.548337,8.408007,1.868634e+13,5.038078e+11
1,Afghanistan,30552000.0,2513,Orge,Vegetaux,360.0,NaN,26.0,2.92,0.24,...,514.0,22.0,NaN,0.0,2.899385e+11,8809669.2,3250.000000,9.875000,1.703000e+12,5.174500e+10
2,Afghanistan,30552000.0,2514,Maïs,Vegetaux,200.0,NaN,21.0,2.50,0.30,...,312.0,5.0,NaN,NaN,2.341811e+11,6244828.8,3066.000000,8.176000,9.596580e+11,2.559088e+10
3,Afghanistan,30552000.0,2517,Millet,Vegetaux,NaN,NaN,3.0,0.40,0.02,...,13.0,0.0,NaN,NaN,3.345444e+10,892118.4,2737.500000,7.300000,3.558750e+10,9.490000e+08
5,Afghanistan,30552000.0,2531,Pommes de Terre,Vegetaux,NaN,NaN,15.0,7.53,0.04,...,303.0,23.0,NaN,NaN,1.672722e+11,2787870.0,727.091633,1.211819,1.904980e+11,3.174967e+09

In [32]:
# Somme de la disponibilité intérieure végétale en protéines des produits dans chaque pays:
dispo_inter_veg_mondiale_prot = dispo_alim_veg['Disponibilité intérieure en protéines (gr.)'].sum()
print(dispo_inter_veg_mondiale_prot)

291967196528669.44

Selon la FAO, le besoin alimentaire global en protéines est de 52 g/personne/jour. Pour donner un peu de souplesse à notre indicateur, nous retenons un niveau de 60g/personne/jour, soit environ 19 kg de protéines par personne/an.

source: Protein and amino acid requirements in Human Nutrition, WHO/FAO, Geneva, 2002,
https://apps.who.int/iris/bitstream/handle/10665/43411/WHO_TRS_935_eng.pdf

In [33]:
besoin_prot_min = 19000

# Population à laquelle la disponibilité intérieure pourrait potentiellement répondre aux besoins en protéines
pop_nourrie_dispo_inter_veg_mondiale_prot = dispo_inter_veg_mondiale_prot / besoin_prot_min
print(pop_nourrie_dispo_inter_veg_mondiale_prot)

15366694554.140497

In [34]:
pourcent_pop_nourrie_dispo_inter_veg_mondiale_prot = pop_nourrie_dispo_inter_veg_mondiale_prot / population_mondiale * 100
print(pourcent_pop_nourrie_dispo_inter_veg_mondiale_prot)

219.608098209809

La production annuelle de produits végétaux pourraient répondre aux besoins caloriques de 15 366 694 554 humains si cette production était dédiée uniquement à l'alimentation, soit 219.6 % de la population mondiale.

<a class='anchor' id='Question8'></a>
## Question 8: Combien d'humains pourraient être nourris si toute la disponibilité alimentaire en produits végétaux, la nourriture végétale destinée aux animaux et les pertes de produits végétaux étaient utilisés pour de la nourriture?

#### Selon les besoins en calorie:

In [35]:
# Ajout d'une colonne quantifiant les calories offertes par: les produits végétaux destinés à l'alimentation, les pertes et la nourrire destinée aux animaux
dispo_alim_veg['Disponibilité alimentaire en Kcal des produits végétaux perdus et destinés aux humains ou aux animaux'] = ((dispo_alim_veg.loc[:, 'Pertes'] + dispo_alim_veg.loc[:, 'Aliments pour animaux']) * 1e6) * dispo_alim_veg.loc[:, 'Ratio Energie-Poids (kcal/kg)'] + dispo_alim_veg.loc[:, 'Disponibilité alimentaire annuelle en Kcal']

# Calcul de la somme
dispo_alim_veg_pertes_anim_kcal = dispo_alim_veg['Disponibilité alimentaire en Kcal des produits végétaux perdus et destinés aux humains ou aux animaux'].sum()
print(dispo_alim_veg_pertes_anim_kcal)

6103629931946425.0

In [36]:
#Population pouvant être nourrie
pop_nourrie_dispo_alim_veg_pertes_anim_kcal = dispo_alim_veg_pertes_anim_kcal / besoin_energ_min
print(pop_nourrie_dispo_alim_veg_pertes_anim_kcal)

8361136893.077294

In [37]:
# Calcul du pourcentage
pourcent_pop_nourrie_dispo_alim_veg_pertes_anim_kcal = pop_nourrie_dispo_alim_veg_pertes_anim_kcal / population_mondiale * 100
print(pourcent_pop_nourrie_dispo_alim_veg_pertes_anim_kcal)

119.49045811324632

La production annuelle de produits végétaux qui est perdue ou destinée à l'alimentation animale et humaine pourrait répondre aux besoins caloriques de 8 361 136 893 humains si cette production était dédiée uniquement à l'alimentation humaine, soit 119,5 % de la population mondiale.

#### Selon les besoins en protéines.

In [38]:
# Ajout d'une colonne quantifiant les protéines apportées par: les pertes et les produits végétaux destinés à l'alimentation animale et humaine
dispo_alim_veg['Disponibilité alimentaire en protéines des produits végétaux perdus ou destinés aux humains et aux animaux'] = (((dispo_alim_veg.loc[:, 'Pertes'] + dispo_alim_veg.loc[:, 'Aliments pour animaux']) * 1e9 * (dispo_alim_veg.loc[:, 'Ratio Protéines-Poids (%)'] / 100)) + (dispo_alim_veg.loc[:, 'Disponibilité de protéines en quantité (g/personne/jour)'] * dispo_alim_veg.loc[:, 'Population'] * 365))

# Calcul de la somme
dispo_veg_pertes_anim_prot = dispo_alim_veg['Disponibilité alimentaire en protéines des produits végétaux perdus ou destinés aux humains et aux animaux'].sum()
print(dispo_veg_pertes_anim_prot)

161033171496619.16

In [39]:
# Population nourrie
pop_nourrie_dispo_inter_veg_pertes_anim_prot = dispo_veg_pertes_anim_prot / besoin_prot_min
print(pop_nourrie_dispo_inter_veg_pertes_anim_prot)

8475430078.769429

In [40]:
#Calcul du pourcentage
pourcent_pop_nourrie_dispo_inter_veg_pertes_anim_prot = pop_nourrie_dispo_inter_veg_pertes_anim_prot / population_mondiale * 100
print(pourcent_pop_nourrie_dispo_inter_veg_pertes_anim_prot)

121.12384186144006

La production annuelle de produits végétaux perdues ou destinée à l'alimentation animale pourrait répondre aux besoins en protéines de 8 475 430 078 humains si cette production était dédiée uniquement à l'alimentation humaine, soit 121.1 % de la population mondiale.

<a class='anchor' id='Question9'></a>
## Question 9: Combien d'humains pourraient être nourris avec la disponibilité alimentaire mondiale?

#### Selon les besoins humains en Kcal

In [41]:
# Somme de la disponibilité alimentaire mondiale des produits végétaux et animaux en Kcal:
dispo_alim_mondiale_kcal = dispo_alim['Disponibilité alimentaire annuelle en Kcal'].sum()
print(dispo_alim_mondiale_kcal)

7357868408890000.0

In [42]:
# Population nourrie
pop_nourrie_dispo_alim_mondiale_kcal = dispo_alim_mondiale_kcal / besoin_energ_min
print(pop_nourrie_dispo_alim_mondiale_kcal)

10079271793.0

In [43]:
# Calcul du pourcentage
pourcent_pop_nourrie_dispo_alim_mondiale_kcal = pop_nourrie_dispo_alim_mondiale_kcal / population_mondiale * 100
print(pourcent_pop_nourrie_dispo_alim_mondiale_kcal)

144.04462208849495

La disponibilité alimentaire mondiale pourrait répondre aux besoins caloriques de 10 079 271 793 humains si sa distribution était équitablement répartie, soit 144 % de la population mondiale.

#### Selon les besoins en protéines

In [44]:
# Somme de la disponibilité alimentaire mondiale des produits végétaux et animaux en protéines (en gr.):
dispo_alim_mondiale_prot = dispo_alim['Disponibilité de protéines annuelle en Kg'].sum() * 1e3
print(dispo_alim_mondiale_kcal)

7357868408890000.0

In [45]:
#Population nourrie
pop_nourrie_dispo_alim_mondiale_prot = dispo_alim_mondiale_prot / besoin_prot_min
print(pop_nourrie_dispo_alim_mondiale_prot)

10898049380.755262

In [46]:
#Calcul du pourcentage
pourcent_pop_nourrie_dispo_alim_mondiale_prot = pop_nourrie_dispo_alim_mondiale_prot / population_mondiale * 100
print(pourcent_pop_nourrie_dispo_alim_mondiale_prot)

155.745914664477

La production agricole mondiale pourrait répondre aux besoins caloriques de 10 898 049 380 humains si cette production était uniquement dédiée à leur alimentation, soit 155,7 % de la population mondiale.

#### Nombre d'humains pouvant être nourris par la disponibilité alimentaire végétale mondiale

#### Selon les besoins humains en Kcal

In [47]:
# Somme de la disponibilité alimentaire mondiale des produits végétaux et animaux en Kcal:
dispo_alim_mondiale_veg_kcal = dispo_alim_veg['Disponibilité alimentaire annuelle en Kcal'].sum()
print(dispo_alim_mondiale_veg_kcal)

6048033046480000.0

In [48]:
#Population nourrie
pop_nourrie_dispo_alim_mondiale_veg_kcal = dispo_alim_mondiale_veg_kcal / besoin_energ_min
print(pop_nourrie_dispo_alim_mondiale_veg_kcal)

8284976776.0

In [49]:
#Calcul du pourcentage
pourcent_pop_nourrie_dispo_alim_mondiale_veg_kcal = pop_nourrie_dispo_alim_mondiale_veg_kcal / population_mondiale * 100
print(pourcent_pop_nourrie_dispo_alim_mondiale_veg_kcal)

118.40204066524842

La disponibilité alimentaire végétale mondiale pourrait répondre aux besoins caloriques de 8 284 976 776 humains si sa distribution était équitablement répartie, soit 118,4 % de la population mondiale.

#### Selon les besoins en protéines

In [50]:
dispo_alim_veg

Élément,Zone,Population,Code Produit,Produit,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Traitement,Variation de stock,Disponibilité alimentaire annuelle en Kcal,Disponibilité de protéines annuelle en Kg,Ratio Energie-Poids (kcal/kg),Ratio Protéines-Poids (%),Disponibilité intérieure en Kcal,Disponibilité intérieure en protéines (gr.),Disponibilité alimentaire en Kcal des produits végétaux perdus et destinés aux humains ou aux animaux,Disponibilité alimentaire en protéines des produits végétaux perdus ou destinés aux humains et aux animaux
0,Afghanistan,30552000.0,2511,Blé,Vegetaux,NaN,NaN,1369.0,160.23,4.69,...,NaN,-350.0,1.526638e+13,4.116011e+08,3118.548337,8.408007,1.868634e+13,5.038078e+11,NaN,NaN
1,Afghanistan,30552000.0,2513,Orge,Vegetaux,360.0,NaN,26.0,2.92,0.24,...,NaN,0.0,2.899385e+11,8.809669e+06,3250.000000,9.875000,1.703000e+12,5.174500e+10,1.628938e+12,4.949467e+10
2,Afghanistan,30552000.0,2514,Maïs,Vegetaux,200.0,NaN,21.0,2.50,0.30,...,NaN,NaN,2.341811e+11,6.244829e+06,3066.000000,8.176000,9.596580e+11,2.559088e+10,9.424271e+11,2.513139e+10
3,Afghanistan,30552000.0,2517,Millet,Vegetaux,NaN,NaN,3.0,0.40,0.02,...,NaN,NaN,3.345444e+10,8.921184e+05,2737.500000,7.300000,3.558750e+10,9.490000e+08,NaN,NaN
5,Afghanistan,30552000.0,2531,Pommes de Terre,Vegetaux,NaN,NaN,15.0,7.53,0.04,...,NaN,NaN,1.672722e+11,2.787870e+06,727.091633,1.211819,1.904980e+11,3.174967e+09,NaN,NaN
6,Afghanistan,30552000.0,2536,"Sucre, canne",Vegetaux,81.0,NaN,NaN,NaN,NaN,...,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Afghanistan,30552000.0,2537,"Sucre, betterave",Vegetaux,0.0,NaN,NaN,NaN,NaN,...,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Afghanistan,30552000.0,2542,Sucre Eq Brut,Vegetaux,NaN,NaN,84.0,8.35,NaN,...,NaN,-19.0,9.367243e+11,NaN,3671.856287,NaN,9.363234e+11,NaN,NaN,NaN
9,Afghanistan,30552000.0,2543,Edulcorants Autres,Vegetaux,NaN,NaN,2.0,0.53,NaN,...,NaN,NaN,2.230296e+10,NaN,1377.358491,NaN,2.203774e+10,NaN,NaN,NaN
10,Afghanistan,30552000.0,2549,Légumineuses Autres,Vegetaux,4.0,NaN,23.0,2.44,0.14,...,NaN,NaN,2.564840e+11,1.739631e+07,3440.573770,23.336066,2.958893e+11,2.006902e+10,2.805681e+11,1.902983e+10
11,Afghanistan,30552000.0,2551,Noix,Vegetaux,NaN,NaN,12.0,1.45,1.07,...,NaN,NaN,1.338178e+11,4.237562e+06,3020.689655,9.565517,1.329103e+11,4.208828e+09,NaN,NaN
12,Afghanistan,30552000.0,2557,Graines de tournesol,Vegetaux,NaN,NaN,NaN,NaN,NaN,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Afghanistan,30552000.0,2559,Graines de coton,Vegetaux,NaN,NaN,NaN,NaN,NaN,...,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Afghanistan,30552000.0,2561,Sésame,Vegetaux,NaN,NaN,9.0,0.52,0.77,...,4.0,0.0,1.003633e+11,3.010900e+06,6317.307692,18.951923,1.326635e+11,3.979904e+09,NaN,NaN
16,Afghanistan,30552000.0,2563,Olives,Vegetaux,NaN,NaN,0.0,0.06,0.03,...,4.0,NaN,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,NaN,NaN
17,Afghanistan,30552000.0,2570,"Plantes Oleiferes, Autre",Vegetaux,NaN,NaN,NaN,NaN,NaN,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Afghanistan,30552000.0,2571,Huile de Soja,Vegetaux,NaN,NaN,13.0,0.53,1.46,...,NaN,NaN,1.449692e+11,NaN,8952.830189,NaN,1.432453e+11,NaN,NaN,NaN
20,Afghanistan,30552000.0,2573,Huile de Tournesol,Vegetaux,NaN,NaN,18.0,0.75,2.06,...,NaN,NaN,2.007266e+11,NaN,8760.000000,NaN,2.014800e+11,NaN,NaN,NaN
21,Afghanistan,30552000.0,2574,Huile de Colza&Moutarde,Vegetaux,NaN,NaN,2.0,0.07,0.18,...,NaN,NaN,2.230296e+10,NaN,10428.571429,NaN,2.085714e+10,NaN,NaN,NaN
22,Afghanistan,30552000.0,2575,Huile Graines de Coton,Vegetaux,NaN,1.0,3.0,0.12,0.34,...,NaN,NaN,3.345444e+10,NaN,9125.000000,NaN,4.562500e+10,NaN,NaN,NaN
23,Afghanistan,30552000.0,2577,Huile de Palme,Vegetaux,NaN,55.0,51.0,2.09,5.74,...,NaN,NaN,5.687255e+11,NaN,8906.698565,NaN,1.059897e+12,NaN,NaN,NaN
24,Afghanistan,30552000.0,2579,Huile de Sésame,Vegetaux,NaN,NaN,1.0,0.05,0.13,...,NaN,NaN,1.115148e+10,NaN,7300.000000,NaN,7.300000e+09,NaN,NaN,NaN
25,Afghanistan,30552000.0,2580,Huile d'Olive,Vegetaux,NaN,NaN,0.0,0.02,0.05,...,NaN,NaN,0.000000e+00,NaN,0.000000,NaN,0.000000e+00,NaN,NaN,NaN
26,Afghanistan,30552000.0,2586,Huil Plantes Oleif Autr,Vegetaux,NaN,359.0,2.0,0.08,0.21,...,NaN,NaN,2.230296e+10,0.000000e+00,9125.000000,0.000000,3.294125e+12,0.000000e+00,NaN,NaN
28,Afghanistan,30552000.0,2605,"Légumes, Autres",Vegetaux,NaN,NaN,17.0,28.97,0.13,...,NaN,NaN,1.895752e+11,9.478758e+06,214.187090,1.070935,2.156864e+11,1.078432e+10,NaN,NaN
29,Afghanistan,30552000.0,2611,"Oranges, Mandarines",Vegetaux,NaN,NaN,4.0,4.75,0.01,...,NaN,NaN,4.460592e+10,7.806036e+05,307.368421,0.537895,4.456842e+10,7.799474e+08,NaN,NaN
30,Afghanistan,30552000.0,2614,"Agrumes, Autres",Vegetaux,NaN,NaN,1.0,1.29,0.01,...,NaN,NaN,1.115148e+10,2.230296e+05,282.945736,0.565891,1.160078e+10,2.320155e+08,NaN,NaN
31,Afghanistan,30552000.0,2615,Bananes,Vegetaux,NaN,NaN,4.0,2.70,0.02,...,NaN,NaN,4.460592e+10,5.575740e+05,540.740741,0.675926,4.434074e+10,5.542593e+08,NaN,NaN
32,Afghanistan,30552000.0,2617,Pommes,Vegetaux,NaN,NaN,3.0,2.22,0.01,...,NaN,NaN,3.345444e+10,2.230296e+05,493.243243,0.328829,3.551351e+10,2.367568e+08,NaN,NaN
34,Afghanistan,30552000.0,2619,Dattes,Vegetaux,NaN,NaN,0.0,0.02,0.00,...,NaN,NaN,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15441,Îles Salomon,561000.0,2573,Huile de Tournesol,Vegetaux,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15442,Îles Salomon,561000.0,2576,Huile de Palmistes,Vegetaux,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15443,Îles Salomon,561000.0,2577,Huile de Palme,Vegetaux,NaN,1.0,52.0,2.14,5.86,...,NaN,0.0,1.064778e+10,NaN,8869.158879,NaN,1.773832e+10,NaN,NaN,NaN
15444,Îles Salomon,561000.0,2578,Huile de Coco,Vegetaux,NaN,10.0,21.0,0.86,2.34,...,NaN,0.0,4.300065e+09,NaN,8912.790698,NaN,8.912791e+10,NaN,NaN,NaN
15445,Îles Salomon,561000.0,2579,Huile de Sésame,Vegetaux,NaN,NaN,0.0,0.01,0.02,...,NaN,NaN,0.000000e+00,NaN,0.000000,NaN,0.000000e+00,NaN,NaN,NaN
15446,Îles Salomon,561000.0,2580,Huile d'Olive,Vegetaux,NaN,NaN,0.0,0.01,0.02,...,NaN,NaN,0.000000e+00,NaN,0.000000,NaN,0.000000e+00,NaN,NaN,NaN
15447,Îles Salomon,561000.0,2582,Huile de Germe de Maïs,Vegetaux,NaN,NaN,0.0,0.01,0.02,...,NaN,NaN,0.000000e+00,NaN,0.000000,NaN,0.000000e+00,NaN,NaN,NaN
15448,Îles Salomon,561000.0,2586,Huil Plantes Oleif Autr,Vegetaux,NaN,0.0,9.0,0.38,1.04,...,NaN,NaN,1.842885e+09,0.000000e+00,8644.736842,0.000000,0.000000e+00,0.000000e+00,NaN,NaN
15449,Îles Salomon,561000.0,2601,Tomates,Vegetaux,NaN,NaN,0.0,0.07,NaN,...,NaN,NaN,0.000000e+00,NaN,0.000000,NaN,0.000000e+00,NaN,NaN,NaN
15450,Îles Salomon,561000.0,2602,Oignons,Vegetaux,NaN,NaN,0.0,0.54,0.00,...,NaN,NaN,0.000000e+00,2.047650e+03,0.000000,0.675926,0.000000e+00,0.000000e+00,NaN,NaN
15451,Îles Salomon,561000.0,2605,"Légumes, Autres",Vegetaux,NaN,NaN,8.0,12.96,0.06,...,NaN,NaN,1.638120e+09,8.600130e+04,225.308642,1.182870,1.802469e+09,9.462963e+07,NaN,NaN
15452,Îles Salomon,561000.0,2611,"Oranges, Mandarines",Vegetaux,NaN,NaN,0.0,1.31,NaN,...,NaN,NaN,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,NaN,NaN
15453,Îles Salomon,561000.0,2613,Pamplemousse,Vegetaux,NaN,NaN,NaN,0.01,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15454,Îles Salomon,561000.0,2614,"Agrumes, Autres",Vegetaux,NaN,NaN,0.0,0.16,NaN,...,NaN,NaN,0.000000e+00,NaN,0.000000,NaN,0.000000e+00,NaN,NaN,NaN
15455,Îles Salomon,561000.0,2615,Bananes,Vegetaux,NaN,NaN,1.0,0.42,0.00,...,NaN,NaN,2.047650e+08,2.047650e+03,869.047619,0.869048,0.000000e+00,0.000000e+00,NaN,NaN
15456,Îles Salomon,561000.0,2617,Pommes,Vegetaux,NaN,NaN,0.0,0.32,NaN,...,NaN,NaN,0.000000e+00,NaN,0.000000,NaN,0.000000e+00,NaN,NaN,NaN
15457,Îles Salomon,561000.0,2618,Ananas,Vegetaux,NaN,NaN,0.0,0.01,NaN,...,NaN,NaN,0.000000e+00,NaN,0.000000,NaN,0.000000e+00,NaN,NaN,NaN
15458,Îles Salomon,561000.0,2620,Raisin,Vegetaux,NaN,NaN,0.0,0.04,NaN,...,NaN,NaN,0.000000e+00,NaN,0.000000,NaN,0.000000e+00,NaN,NaN,NaN
15459,Îles Salomon,561000.0,2625,"Fruits, Autres",Vegetaux,NaN,NaN,59.0,49.35,0.63,...,NaN,NaN,1.208114e+10,1.330972e+05,436.372847,0.480750,1.265481e+10,1.394174e+08,NaN,NaN
15460,Îles Salomon,561000.0,2630,Café,Vegetaux,NaN,NaN,1.0,1.05,NaN,...,NaN,NaN,2.047650e+08,3.890535e+04,347.619048,6.604762,3.476190e+08,6.604762e+07,NaN,NaN
15461,Îles Salomon,561000.0,2633,Feve de Cacao,Vegetaux,NaN,NaN,4.0,0.41,0.42,...,NaN,-1.0,8.190600e+08,1.023825e+04,3560.975610,4.451220,0.000000e+00,0.000000e+00,NaN,NaN
15462,Îles Salomon,561000.0,2635,Thé,Vegetaux,NaN,NaN,0.0,0.17,NaN,...,NaN,NaN,0.000000e+00,8.190600e+03,0.000000,8.588235,0.000000e+00,0.000000e+00,NaN,NaN
15464,Îles Salomon,561000.0,2645,"Épices, Autres",Vegetaux,NaN,NaN,4.0,0.48,0.21,...,NaN,NaN,8.190600e+08,3.071475e+04,3041.666667,11.406250,0.000000e+00,0.000000e+00,NaN,NaN
15465,Îles Salomon,561000.0,2655,Vin,Vegetaux,NaN,NaN,0.0,0.07,NaN,...,NaN,NaN,0.000000e+00,NaN,0.000000,NaN,0.000000e+00,NaN,NaN,NaN
15466,Îles Salomon,561000.0,2656,Bière,Vegetaux,NaN,NaN,8.0,6.55,NaN,...,NaN,NaN,1.638120e+09,1.842885e+04,445.801527,0.501527,1.783206e+09,2.006107e+07,NaN,NaN
15468,Îles Salomon,561000.0,2658,Boissons Alcooliques,Vegetaux,NaN,NaN,0.0,0.03,NaN,...,NaN,0.0,0.000000e+00,NaN,0.000000,NaN,0.000000e+00,NaN,NaN,NaN
15469,Îles Salomon,561000.0,2659,"Alcool, non Comestible",Vegetaux,NaN,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15470,Îles Salomon,561000.0,2680,Aliments pour enfants,Vegetaux,NaN,NaN,0.0,0.03,NaN,...,NaN,NaN,0.000000e+00,2.047650e+03,0.000000,12.166667,0.000000e+00,0.000000e+00,NaN,NaN
15492,Îles Salomon,561000.0,2805,Riz (Eq Blanchi),Vegetaux,0.0,12.0,623.0,63.76,1.36,...,NaN,0.0,1.275686e+11,2.231938e+06,3566.420954,6.239806,1.747546e+11,3.057505e+09,1.311350e+11,2.294337e+09
15494,Îles Salomon,561000.0,2899,Miscellanees,Vegetaux,NaN,NaN,3.0,NaN,0.04,...,NaN,NaN,6.142950e+08,2.047650e+04,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
# Somme de la disponibilité alimentaire mondiale des produits végétaux en protéines (en gr.):
dispo_alim_mondiale_veg_prot = dispo_alim_veg['Disponibilité de protéines annuelle en Kg'].sum() * 1e3
print(dispo_alim_mondiale_veg_prot)

125183999673799.98

In [52]:
#Population nourrie
pop_nourrie_dispo_alim_mondiale_veg_prot = dispo_alim_mondiale_veg_prot / besoin_prot_min
print(pop_nourrie_dispo_alim_mondiale_veg_prot)

6588631561.778947

In [53]:
#Calcul du pourcentage
pourcent_pop_nourrie_dispo_alim_mondiale_veg_prot = pop_nourrie_dispo_alim_mondiale_veg_prot / population_mondiale * 100
print(pourcent_pop_nourrie_dispo_alim_mondiale_veg_prot)

94.15927686917756

La disponibilité alimentaire végétale mondiale pourrait répondre aux besoins en protéines de 6 588 631 561 humains, soit 94,2 % de la population mondiale.

#### Nombre d'humains pouvant être nourris par la disponibilité alimentaire animale mondiale

#### Selon les besoins humains en Kcal

In [54]:
# Création de la table recensant les diverses utilisations de la production agricole animale
dispo_alim_anim = dispo_alim.loc[dispo_alim.Origine == 'Animaux']

# Somme de la disponibilité alimentaire mondiale des produits animaux en Kcal:
dispo_alim_mondiale_anim_kcal = dispo_alim_anim['Disponibilité alimentaire annuelle en Kcal'].sum()
print(dispo_alim_mondiale_anim_kcal)

1309835362410000.0

In [55]:
#Population nourrie
pop_nourrie_dispo_alim_mondiale_anim_kcal = dispo_alim_mondiale_anim_kcal / besoin_energ_min
print(pop_nourrie_dispo_alim_mondiale_anim_kcal)

1794295017.0

In [56]:
#Calcul du pourcentage
pourcent_pop_nourrie_dispo_alim_mondiale_anim_kcal = pop_nourrie_dispo_alim_mondiale_anim_kcal / population_mondiale * 100
print(pourcent_pop_nourrie_dispo_alim_mondiale_anim_kcal)

25.642581423246536

La disponibilité alimentaire mondiale des produits animaliers pourrait répondre aux besoins caloriques de 1 794 295 017 humains si sa distribution était équitablement répartie, soit 25,6 % de la population mondiale.

#### Selon les besoins en protéines

In [57]:
# Somme de la disponibilité alimentaire mondiale des produits animaliers en protéines (en gr.):
dispo_alim_mondiale_anim_prot = dispo_alim_anim['Disponibilité de protéines annuelle en Kg'].sum() * 1e3
print(dispo_alim_mondiale_anim_prot)

81878938560549.98

In [58]:
#Population nourrie
pop_nourrie_dispo_alim_mondiale_anim_prot = dispo_alim_mondiale_anim_prot / besoin_prot_min
print(pop_nourrie_dispo_alim_mondiale_anim_prot)

4309417818.976315

In [59]:
#Calcul du pourcentage
pourcent_pop_nourrie_dispo_alim_mondiale_veg_prot = pop_nourrie_dispo_alim_mondiale_veg_prot / population_mondiale * 100
print(pourcent_pop_nourrie_dispo_alim_mondiale_veg_prot)

94.15927686917756

La production agricole mondiale des produits animaliers pourrait répondre aux besoins en protéines de 4 309 417 818 humains si cette production était uniquement dédiée à leur alimentation, soit 94,2 % de la population mondiale.

<a class='anchor' id='Question10'></a>
## Question 10: Quelle proportion de la population mondiale est considérée comme étant en sous-nutrition ?

In [60]:
sous_alim.head()

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20122014,2012-2014,millions,7.9,F,Estimation FAO,NaN
1,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20132015,2013-2015,millions,8.8,F,Estimation FAO,NaN
2,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20142016,2014-2016,millions,9.6,F,Estimation FAO,NaN
3,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20152017,2015-2017,millions,10.2,F,Estimation FAO,NaN
4,FS,Données de la sécurité alimentaire,2,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20162018,2016-2018,millions,10.6,F,Estimation FAO,NaN

In [61]:
sous_alim.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 15 columns):
Code Domaine              1020 non-null object
Domaine                   1020 non-null object
Code zone                 1020 non-null int64
Zone                      1020 non-null object
Code Élément              1020 non-null int64
Élément                   1020 non-null object
Code Produit              1020 non-null int64
Produit                   1020 non-null object
Code année                1020 non-null int64
Année                     1020 non-null object
Unité                     1020 non-null object
Valeur                    605 non-null object
Symbole                   1020 non-null object
Description du Symbole    1020 non-null object
Note                      0 non-null float64
dtypes: float64(1), int64(4), object(10)
memory usage: 119.6+ KB

In [62]:
sous_alim[['Valeur']]

     Valeur
0       7.9
1       8.8
2       9.6
3      10.2
4      10.6
5       2.6
6       2.8
7       3.2
8       3.4
9       3.5
10      0.2
11      0.2
12      0.2
13      0.2
14      0.2
15      1.7
16      1.6
17      1.6
18      1.6
19      1.6
20      NaN
21      NaN
22      NaN
23      NaN
24      NaN
25      NaN
26      NaN
27      NaN
28      NaN
29      NaN
...     ...
990    <0.1
991    <0.1
992    <0.1
993    <0.1
994    <0.1
995     1.9
996     2.9
997     4.3
998     5.7
999     6.8
1000   10.4
1001    9.7
1002    9.2
1003    8.9
1004    8.8
1005    7.2
1006    8.2
1007    9.3
1008   10.4
1009     11
1010      7
1011      7
1012    7.2
1013    7.6
1014      8
1015    6.6
1016    7.2
1017    7.8
1018    8.2
1019    8.5

[1020 rows x 1 columns]

In [63]:
# Suppression des caractères '<', '=' et '>'
sous_alim[['Valeur']].replace({'<':'', '=':'', '>':''}, regex=True)

     Valeur
0       7.9
1       8.8
2       9.6
3      10.2
4      10.6
5       2.6
6       2.8
7       3.2
8       3.4
9       3.5
10      0.2
11      0.2
12      0.2
13      0.2
14      0.2
15      1.7
16      1.6
17      1.6
18      1.6
19      1.6
20      NaN
21      NaN
22      NaN
23      NaN
24      NaN
25      NaN
26      NaN
27      NaN
28      NaN
29      NaN
...     ...
990     0.1
991     0.1
992     0.1
993     0.1
994     0.1
995     1.9
996     2.9
997     4.3
998     5.7
999     6.8
1000   10.4
1001    9.7
1002    9.2
1003    8.9
1004    8.8
1005    7.2
1006    8.2
1007    9.3
1008   10.4
1009     11
1010      7
1011      7
1012    7.2
1013    7.6
1014      8
1015    6.6
1016    7.2
1017    7.8
1018    8.2
1019    8.5

[1020 rows x 1 columns]

#### Nettoyage de la base de données 'sous_alim'

In [64]:
# Suppression de la ligne dédiée à la Zone 'Chine'
sous_alim.drop(sous_alim.loc[sous_alim.Zone == 'Chine'].index, inplace=True)

In [65]:
# Suppression des colonnes inutiles
sous_alim.drop(columns=['Code Domaine', 'Domaine', 'Code Élément', 'Élément', 'Code Produit', 'Produit', 'Code année', 'Unité', 'Symbole', 'Description du Symbole', 'Note'], inplace=True)

# Remplacement de l'intitulé de la colonne 'Valeur' par 'Population'
sous_alim.rename(columns={'Valeur': 'Population'}, inplace=True)

In [66]:
# Suppression des lignes nulles
sous_alim.drop(sous_alim.loc[sous_alim['Population'].isnull()].index, inplace=True)

In [67]:
sous_alim.dtypes

Code zone      int64
Zone          object
Année         object
Population    object
dtype: object

#### La colonne 'Population' n'est pas constituée de valeurs numériques mais de caractères

In [68]:
## Conversion des valeurs de la colonne 'Population' en numérique
sous_alim['Population'] = pd.to_numeric(sous_alim['Population'], errors='coerce')

In [69]:
sous_alim['Population'] = sous_alim['Population'].fillna(0)

In [70]:
sous_alim['Population'] = sous_alim['Population'] * 1e6

In [71]:
sous_alim.dtypes

Code zone       int64
Zone           object
Année          object
Population    float64
dtype: object

In [72]:
# Création d'une table pivot référençant la population en sous-alimentation pour chque période
sous_alim_pays_annee = sous_alim.pivot_table('Population', index='Zone', columns='Année', aggfunc='sum')
sous_alim_pays_annee

Année,2012-2014,2013-2015,2014-2016,2015-2017,2016-2018
Zone,,,,,
Afghanistan,7900000.0,8800000.0,9600000.0,10200000.0,10600000.0
Afrique du Sud,2600000.0,2800000.0,3200000.0,3400000.0,3500000.0
Albanie,200000.0,200000.0,200000.0,200000.0,200000.0
Algérie,1700000.0,1600000.0,1600000.0,1600000.0,1600000.0
Angola,8100000.0,7600000.0,7400000.0,7400000.0,7400000.0
Arabie saoudite,1600000.0,1600000.0,1800000.0,2000000.0,2300000.0
Argentine,1500000.0,1500000.0,1600000.0,1800000.0,2100000.0
Arménie,100000.0,100000.0,100000.0,100000.0,100000.0
Bangladesh,26100000.0,25800000.0,25300000.0,24700000.0,24200000.0
Barbade,0.0,0.0,0.0,0.0,0.0
Belize,0.0,0.0,0.0,0.0,0.0
Bolivie (État plurinational de),2200000.0,2000000.0,1900000.0,1900000.0,1900000.0
Botswana,500000.0,500000.0,600000.0,600000.0,600000.0
Brunéi Darussalam,0.0,0.0,0.0,0.0,0.0
Bulgarie,400000.0,300000.0,300000.0,300000.0,300000.0
Burkina Faso,3400000.0,3500000.0,3600000.0,3700000.0,3800000.0
Bénin,1000000.0,1000000.0,1000000.0,1100000.0,1100000.0
Cabo Verde,0.0,0.0,0.0,0.0,0.0
Cambodge,2800000.0,2800000.0,2800000.0,2700000.0,2600000.0
Cameroun,1700000.0,1600000.0,1800000.0,2000000.0,2400000.0
Chili,600000.0,600000.0,600000.0,500000.0,500000.0
Chine - RAS de Macao,0.0,0.0,0.0,0.0,0.0
"Chine, Taiwan Province de",1000000.0,900000.0,900000.0,800000.0,800000.0
"Chine, continentale",136600000.0,129000000.0,124000000.0,122100000.0,121400000.0
Chypre,0.0,0.0,0.0,0.0,0.0
Colombie,4100000.0,3600000.0,3100000.0,2700000.0,2400000.0
Congo,1800000.0,1900000.0,1900000.0,2000000.0,2100000.0
Costa Rica,300000.0,300000.0,200000.0,200000.0,200000.0
Côte d'Ivoire,4700000.0,4700000.0,4700000.0,4700000.0,4600000.0
Djibouti,200000.0,200000.0,200000.0,200000.0,200000.0
...,...,...,...,...,...
République-Unie de Tanzanie,16400000.0,16700000.0,17000000.0,17200000.0,17600000.0
Saint-Vincent-et-les Grenadines,0.0,0.0,0.0,0.0,0.0
Samoa,0.0,0.0,0.0,0.0,0.0
Sao Tomé-et-Principe,0.0,0.0,0.0,0.0,0.0
Serbie,500000.0,500000.0,500000.0,500000.0,500000.0
Sierra Leone,1600000.0,1600000.0,1700000.0,1800000.0,1900000.0
Slovaquie,200000.0,200000.0,200000.0,200000.0,200000.0
Soudan,8300000.0,7900000.0,7800000.0,7900000.0,8200000.0
Sri Lanka,2300000.0,2100000.0,2000000.0,1900000.0,1900000.0
Suriname,0.0,0.0,0.0,0.0,0.0
Sénégal,1900000.0,1900000.0,1900000.0,1900000.0,1800000.0
Tchad,4900000.0,5000000.0,5100000.0,5300000.0,5600000.0
Thaïlande,5600000.0,5500000.0,5400000.0,5400000.0,5400000.0
Timor-Leste,300000.0,300000.0,300000.0,300000.0,300000.0
Togo,1300000.0,1300000.0,1300000.0,1300000.0,1300000.0
Trinité-et-Tobago,0.0,0.0,0.0,0.0,0.0
Tunisie,500000.0,500000.0,500000.0,500000.0,500000.0
Turkménistan,300000.0,300000.0,300000.0,300000.0,300000.0
Ukraine,NaN,NaN,1300000.0,1500000.0,1500000.0
Vanuatu,0.0,0.0,0.0,0.0,0.0
Venezuela (République bolivarienne du),1900000.0,2900000.0,4300000.0,5700000.0,6800000.0
Viet Nam,10400000.0,9700000.0,9200000.0,8900000.0,8800000.0
Yémen,7200000.0,8200000.0,9300000.0,10400000.0,11000000.0
Zambie,7000000.0,7000000.0,7200000.0,7600000.0,8000000.0
Zimbabwe,6600000.0,7200000.0,7800000.0,8200000.0,8500000.0
Égypte,3900000.0,4000000.0,4100000.0,4200000.0,4400000.0
Émirats arabes unis,400000.0,300000.0,300000.0,300000.0,200000.0
Équateur,1300000.0,1300000.0,1300000.0,1300000.0,1300000.0
Éthiopie,25300000.0,23800000.0,22700000.0,21900000.0,21600000.0
Îles Salomon,0.0,0.0,0.0,0.0,0.0

In [73]:
# Somme de la population en sous-nutrition en 2012-2014 rapportée à la population mondiale en 2013:
pop_sous_alim = sous_alim_pays_annee['2012-2014'].sum() / population_mondiale * 100
print(pop_sous_alim)

10.628345742359295

En 2013, environ 10,6% de la population était en sous-nutrition.

<a class='anchor' id='Question11'></a>
## Question 11: Quelle proportion des céréales destinées à l'alimentation a pour fin l'alimentation animale?

In [74]:
# Identification des Code Produits associés aux céréales
code_prod_cereal = cereales['Code Produit'].unique()
code_prod_cereal

array([2511, 2805, 2513, 2514, 2517, 2515, 2516, 2518, 2520], dtype=int64)

In [75]:
# Ajout d'une colonne identifiant les lignes associées à la production céréalière
dispo_alim['is_cereal'] = dispo_alim['Code Produit'].isin(code_prod_cereal)

# Restriction de la table pivot aux produits céréaliers
dispo_alim_cereal = dispo_alim.loc[dispo_alim['is_cereal'] == True]
dispo_alim_cereal.head()

Élément,Zone,Population,Code Produit,Produit,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Pertes,Production,Semences,Traitement,Variation de stock,Disponibilité alimentaire annuelle en Kcal,Disponibilité de protéines annuelle en Kg,Ratio Energie-Poids (kcal/kg),Ratio Protéines-Poids (%),is_cereal
0,Afghanistan,30552000.0,2511,Blé,Vegetaux,NaN,NaN,1369.0,160.23,4.69,...,775.0,5169.0,322.0,NaN,-350.0,1.526638e+13,411601126.8,3118.548337,8.408007,True
1,Afghanistan,30552000.0,2513,Orge,Vegetaux,360.0,NaN,26.0,2.92,0.24,...,52.0,514.0,22.0,NaN,0.0,2.899385e+11,8809669.2,3250.000000,9.875000,True
2,Afghanistan,30552000.0,2514,Maïs,Vegetaux,200.0,NaN,21.0,2.50,0.30,...,31.0,312.0,5.0,NaN,NaN,2.341811e+11,6244828.8,3066.000000,8.176000,True
3,Afghanistan,30552000.0,2517,Millet,Vegetaux,NaN,NaN,3.0,0.40,0.02,...,1.0,13.0,0.0,NaN,NaN,3.345444e+10,892118.4,2737.500000,7.300000,True
57,Afghanistan,30552000.0,2805,Riz (Eq Blanchi),Vegetaux,NaN,NaN,141.0,13.82,0.27,...,24.0,342.0,14.0,NaN,NaN,1.572359e+12,30108996.0,3723.950796,7.130970,True

In [76]:
# Calcul du taux de céréales destinées à l'alimentation animale
taux_cereales_alim_animaux = dispo_alim_cereal['Aliments pour animaux'].sum() / (dispo_alim_cereal['Aliments pour animaux'].sum() + dispo_alim_cereal['Nourriture'].sum()) * 100
print(taux_cereales_alim_animaux)

45.58885349055481

En 2013, 45,6% de la production céréalière destinée à l'alimentation était vouée aux animaux.

<a class='anchor' id='Question12'></a>
## Question 12: Donnez les 3 produits qui ont la plus grande valeur dans les pays sous-alimentés pour chacun des 2 ratios

In [77]:
# Identification des pays recensés dans la table sous_alimentation.csv
pays_sous_alim = sous_alim.Zone.unique()
pays_sous_alim

array(['Afghanistan', 'Afrique du Sud', 'Albanie', 'Algérie', 'Angola',
       'Arabie saoudite', 'Argentine', 'Arménie', 'Bangladesh', 'Barbade',
       'Belize', 'Bénin', 'Bolivie (État plurinational de)', 'Botswana',
       'Brunéi Darussalam', 'Bulgarie', 'Burkina Faso', 'Cabo Verde',
       'Cambodge', 'Cameroun', 'Chili', 'Chine - RAS de Macao',
       'Chine, continentale', 'Chine, Taiwan Province de', 'Chypre',
       'Colombie', 'Congo', 'Costa Rica', "Côte d'Ivoire", 'Djibouti',
       'Dominique', 'Égypte', 'El Salvador', 'Émirats arabes unis',
       'Équateur', 'Estonie', 'Eswatini', 'Éthiopie', 'Fidji', 'Gabon',
       'Gambie', 'Géorgie', 'Ghana', 'Guatemala', 'Guinée',
       'Guinée-Bissau', 'Guyana', 'Haïti', 'Honduras', 'Îles Salomon',
       'Inde', 'Indonésie', "Iran (République islamique d')", 'Iraq',
       'Jamaïque', 'Jordanie', 'Kenya', 'Kirghizistan', 'Kiribati',
       'Koweït', 'Lesotho', 'Liban', 'Libéria', 'Macédoine du Nord',
       'Madagascar', 'Malaisie', 'Malawi', 'Maldives', 'Mali', 'Maroc',
       'Maurice', 'Mauritanie', 'Mexique', 'Mongolie', 'Mozambique',
       'Myanmar', 'Namibie', 'Népal', 'Nicaragua', 'Niger', 'Nigéria',
       'Nouvelle-Calédonie', 'Oman', 'Ouganda', 'Ouzbékistan', 'Pakistan',
       'Panama', 'Paraguay', 'Pérou', 'Philippines',
       'Polynésie française', 'République centrafricaine',
       'République démocratique populaire lao', 'République dominicaine',
       'République populaire démocratique de Corée',
       'République-Unie de Tanzanie', 'Rwanda',
       'Saint-Vincent-et-les Grenadines', 'Samoa', 'Sao Tomé-et-Principe',
       'Sénégal', 'Serbie', 'Sierra Leone', 'Slovaquie', 'Soudan',
       'Sri Lanka', 'Suriname', 'Tchad', 'Thaïlande', 'Timor-Leste',
       'Togo', 'Trinité-et-Tobago', 'Tunisie', 'Turkménistan', 'Ukraine',
       'Vanuatu', 'Venezuela (République bolivarienne du)', 'Viet Nam',
       'Yémen', 'Zambie', 'Zimbabwe'], dtype=object)

In [78]:
# Ajout d'une colonne dans la table 'sous_alim' permettant de repérer les pays touchés par la sous-alimentation
dispo_alim['sous_alimenté'] = dispo_alim.Zone.isin(pays_sous_alim)

# Restriction de la table 'sous_alim' aux pays touché par la sous-alimentation
dispo_alim_sous_alim = dispo_alim.loc[dispo_alim['sous_alimenté'] == True]

In [79]:
# Aggrégation de la table 'sous_alim' par produit
produits_sous_alim = dispo_alim_sous_alim.groupby('Produit').sum()

# Classement des 15 produits les plus exportés par les pays touchés par la sous-alimentation et leurs quantités exportées (en milliers de tonnes)
produits_export = produits_sous_alim.nlargest(15, 'Exportations - Quantité')[['Exportations - Quantité']]
produits_export

Élément              Exportations - Quantité
Produit
Maïs                                 54341.0
Huile de Palme                       46326.0
Manioc                               35846.0
Blé                                  33756.0
Riz (Eq Blanchi)                     33122.0
Sucre Eq Brut                        26326.0
Légumes, Autres                      20281.0
Bananes                              17996.0
Lait - Excl Beurre                   15899.0
Fruits, Autres                       14831.0
Poissons Pelagiques                  14247.0
Tomates                               9138.0
Pommes                                8435.0
Oranges, Mandarines                   7193.0
Ananas                                6418.0

Les 15 produits les plus exportés par les pays touchés par la sous-alimentation sont dans l'ordre décroissant:
Maïs, Huile de Palme, Manioc, Blé, Riz (Eq Blanchi), Sucre Eq Brut, Légumes, Autres, Bananes, Lait - Excl Beurre, Fruits, Poissons Pelagiques, Tomates, Pommes, Oranges & Mandarines, Ananas

In [80]:
# Restriction de la table 'dispo_alim' aux 15 produits les plus exportés par les pays touchés par la sous-alimentation
dispo_alim_15_prod_export = dispo_alim.loc[(dispo_alim.Produit == 'Maïs') | (dispo_alim.Produit == 'Huile de Palme') | (dispo_alim.Produit == 'Manioc') | (dispo_alim.Produit == 'Blé') | (dispo_alim.Produit == 'Riz (Eq Blanchi)') | (dispo_alim.Produit == 'Sucre Eq Brut') | (dispo_alim.Produit == 'Légumes, Autres') | (dispo_alim.Produit == 'Bananes') | (dispo_alim.Produit == 'Lait - Excl Beurre') | (dispo_alim.Produit == 'Fruits, Autres') | (dispo_alim.Produit == 'Poissons Pelagiques') | (dispo_alim.Produit == 'Tomates') | (dispo_alim.Produit == 'Pommes') | (dispo_alim.Produit == 'Oranges, Mandarines') | (dispo_alim.Produit == 'Ananas')]

# Classement des 200 plus fortes importations de ces 15 produits
dispo_alim_200_prod_import = dispo_alim_15_prod_export.nlargest(200, 'Importations - Quantité')
dispo_alim_200_prod_import

# Aggrégation de ces importations par produit en Milliers de Tonnes
dispo_alim_200_prod_import_agg = dispo_alim_200_prod_import.groupby('Produit').sum()
dispo_alim_200_prod_import_agg[['Importations - Quantité']].sort_values(by='Importations - Quantité', ascending=False)

Élément              Importations - Quantité
Produit
Blé                                 152582.0
Maïs                                105410.0
Lait - Excl Beurre                   91444.0
Sucre Eq Brut                        35206.0
Manioc                               34655.0
Huile de Palme                       29138.0
Légumes, Autres                      28177.0
Oranges, Mandarines                  22945.0
Fruits, Autres                       16726.0
Riz (Eq Blanchi)                     13990.0
Poissons Pelagiques                  13445.0
Bananes                              10638.0
Pommes                                8518.0
Tomates                               7143.0
Ananas                                2049.0

In [81]:
# Suppression des valeurs nulles des dénominateurs des ratios
dispo_alim_200_prod_import_agg.drop(dispo_alim_200_prod_import_agg.loc[(dispo_alim_200_prod_import_agg['Disponibilité intérieure'] == 0)].index, inplace=True)
dispo_alim_200_prod_import_agg.drop(dispo_alim_200_prod_import_agg.loc[(dispo_alim_200_prod_import_agg['Nourriture'] == 0)].index, inplace=True)

# Ajout d'une colonne désignant le ratio entre la quantité destinée aux "Autres utilisations" (Other uses) et la disponibilité intérieure
dispo_alim_200_prod_import_agg['Ratio autres utilisations - disponinilité intérieure'] = (dispo_alim_200_prod_import_agg.loc[:, 'Autres utilisations (non alimentaire)']) / (dispo_alim_200_prod_import_agg.loc[:, 'Disponibilité intérieure']) * 100

# Ajout d'une colonne désignant le ratio entre la quantité destinée à la nourriture animale et la quantité destinée à la nourriture (animale + humaine)
dispo_alim_200_prod_import_agg['Ratio nourriture animale - nourriture animale et humaine'] = (dispo_alim_200_prod_import_agg.loc[:, 'Aliments pour animaux']) / ((dispo_alim_200_prod_import_agg.loc[:, 'Aliments pour animaux']) + (dispo_alim_200_prod_import_agg.loc[:, 'Nourriture'])) * 100

dispo_alim_200_prod_import_agg[['Ratio autres utilisations - disponinilité intérieure', 'Ratio nourriture animale - nourriture animale et humaine']]

Élément,Ratio autres utilisations - disponinilité intérieure,Ratio nourriture animale - nourriture animale et humaine
Produit,,
Ananas,0.000000,0.000000
Bananes,0.000000,0.000000
Blé,3.405598,24.441119
"Fruits, Autres",0.016400,0.000000
Huile de Palme,69.659782,0.000000
Lait - Excl Beurre,3.317437,8.593388
"Légumes, Autres",0.000000,4.994290
Manioc,30.233491,62.240756
Maïs,24.017418,87.839106
"Oranges, Mandarines",0.005119,0.000000
Poissons Pelagiques,0.000000,75.535947
Pommes,0.000000,0.000000
Riz (Eq Blanchi),1.866422,9.333018
Sucre Eq Brut,4.422970,0.000000
Tomates,0.000000,0.000000

In [82]:
ratio_autres_utilisations = dispo_alim_200_prod_import_agg.nlargest(3, 'Ratio autres utilisations - disponinilité intérieure')
ratio_autres_utilisations[['Ratio autres utilisations - disponinilité intérieure']]

Élément         Ratio autres utilisations - disponinilité intérieure
Produit
Huile de Palme                                          69.659782
Manioc                                                  30.233491
Maïs                                                    24.017418

#### Parmi les produits agricoles les plus exportés par les pays touchés par la sous-alimentation, l'huile de palme, le manioc et le maïs sont les produits les plus sollicités pour utilisations diverses dans la disponibilité intérieure de leurs pays importateurs.

In [83]:
ratio_nourriture_animale = dispo_alim_200_prod_import_agg.nlargest(3, 'Ratio nourriture animale - nourriture animale et humaine')
ratio_nourriture_animale[['Ratio nourriture animale - nourriture animale et humaine']]

Élément              Ratio nourriture animale - nourriture animale et humaine
Produit
Maïs                                                         87.839106
Poissons Pelagiques                                          75.535947
Manioc                                                       62.240756

#### Parmi les produits agricoles les plus exportés par les pays touchés par la sous-alimentation, le maïs, les poissons pélagiques et le manioc sont les produits les plus courrament destinés à l'alimentation animale

### Exercice alternatif: avec les pays dont la part de la population en sous-alimentation est supérieure à 20%

In [84]:
# Jointure
left = sous_alim.set_index('Code zone')
right = population.set_index('Code zone')
sous_alim_pop = left.join(right, lsuffix='_sous_alim', rsuffix='_pop')

In [85]:
# Restriction des lignes concernant les années 2012-2014 pour rendre la jointure avec la table 'population' de 2013 plus cohérente
sous_alim_pop = sous_alim_pop.loc[sous_alim_pop['Année_sous_alim'] == '2012-2014']

In [86]:
# Suppression des lignes inutiles
sous_alim_pop = sous_alim_pop.drop(columns=['Année_sous_alim', 'Zone_sous_alim'])

In [87]:
pop_sous_alimentee = sous_alim_pop['Population_sous_alim'].sum() / population_mondiale * 100
pop_sous_alimentee

10.628345742359295

#### En 2013, 10,6% de la population mondiale était en situation de sous-alimentation

In [88]:
# Ajout d'une colonne précisant la part de la population sous-alimentée dans chaque pays
sous_alim_pop['Part de la population sous-alimentatée'] = sous_alim_pop.loc[:, 'Population_sous_alim'] / sous_alim_pop.loc[:, 'Population_pop'] * 100

# Identification des pays dont la part de la population en sous-alimentation est supérieure à 20%
pays_sous_alim_sup20 = sous_alim_pop[['Zone_pop', 'Part de la population sous-alimentatée']].loc[sous_alim_pop['Part de la population sous-alimentatée'] > 20]
pays_sous_alim_sup20.sort_values(by='Part de la population sous-alimentatée', ascending=False)

,Zone_pop,Part de la population sous-alimentatée
Code zone,,
93,Haïti,50.402249
251,Zambie,48.146365
181,Zimbabwe,46.643110
37,République centrafricaine,43.327556
116,République populaire démocratique de Corée,42.578831
46,Congo,40.467626
39,Tchad,38.206628
7,Angola,37.723547
123,Libéria,37.261295
129,Madagascar,35.768811
226,Ouganda,33.529365
215,République-Unie de Tanzanie,33.297464
184,Rwanda,30.568056
147,Namibie,30.395137
249,Yémen,29.499734
144,Mozambique,27.096075
103,Iraq,26.950985
238,Éthiopie,26.886005
176,Timor-Leste,26.478376
197,Sierra Leone,26.263953
2,Afghanistan,25.857554
20,Botswana,24.740228
209,Eswatini,24.000000
175,Guinée-Bissau,23.474178
107,Côte d'Ivoire,23.134475
72,Djibouti,22.909507
114,Kenya,22.545881
276,Soudan,21.862817
165,Pakistan,20.917631
19,Bolivie (État plurinational de),20.616624
233,Burkina Faso,20.076764

In [89]:
# Classement des pays selon la part de la population étant sous-alimentée
sous_alim_pop.sort_values(by='Part de la population sous-alimentatée', ascending=False)

,Population_sous_alim,Zone_pop,Année_pop,Population_pop,Part de la population sous-alimentatée
Code zone,,,,,
93,5200000.0,Haïti,2013,10317000.0,50.402249
251,7000000.0,Zambie,2013,14539000.0,48.146365
181,6600000.0,Zimbabwe,2013,14150000.0,46.643110
37,2000000.0,République centrafricaine,2013,4616000.0,43.327556
116,10600000.0,République populaire démocratique de Corée,2013,24895000.0,42.578831
46,1800000.0,Congo,2013,4448000.0,40.467626
39,4900000.0,Tchad,2013,12825000.0,38.206628
7,8100000.0,Angola,2013,21472000.0,37.723547
123,1600000.0,Libéria,2013,4294000.0,37.261295
129,8200000.0,Madagascar,2013,22925000.0,35.768811
226,12600000.0,Ouganda,2013,37579000.0,33.529365
215,16400000.0,République-Unie de Tanzanie,2013,49253000.0,33.297464
184,3600000.0,Rwanda,2013,11777000.0,30.568056
147,700000.0,Namibie,2013,2303000.0,30.395137
249,7200000.0,Yémen,2013,24407000.0,29.499734
144,7000000.0,Mozambique,2013,25834000.0,27.096075
103,9100000.0,Iraq,2013,33765000.0,26.950985
238,25300000.0,Éthiopie,2013,94101000.0,26.886005
176,300000.0,Timor-Leste,2013,1133000.0,26.478376
197,1600000.0,Sierra Leone,2013,6092000.0,26.263953
2,7900000.0,Afghanistan,2013,30552000.0,25.857554
20,500000.0,Botswana,2013,2021000.0,24.740228
209,300000.0,Eswatini,2013,1250000.0,24.000000
175,400000.0,Guinée-Bissau,2013,1704000.0,23.474178
107,4700000.0,Côte d'Ivoire,2013,20316000.0,23.134475
72,200000.0,Djibouti,2013,873000.0,22.909507
114,10000000.0,Kenya,2013,44354000.0,22.545881
276,8300000.0,Soudan,2013,37964000.0,21.862817
165,38100000.0,Pakistan,2013,182143000.0,20.917631
19,2200000.0,Bolivie (État plurinational de),2013,10671000.0,20.616624
...,...,...,...,...,...
225,400000.0,Émirats arabes unis,2013,9346000.0,4.279906
143,1400000.0,Maroc,2013,33008000.0,4.241396
199,200000.0,Slovaquie,2013,5450000.0,3.669725
9,1500000.0,Argentine,2013,41446000.0,3.619167
40,600000.0,Chili,2013,17620000.0,3.405221
131,1000000.0,Malaisie,2013,29717000.0,3.365077
1,100000.0,Arménie,2013,2977000.0,3.359086
193,0.0,Sao Tomé-et-Principe,2013,193000.0,0.000000
23,0.0,Belize,2013,332000.0,0.000000
70,0.0,Polynésie française,2013,277000.0,0.000000
66,0.0,Fidji,2013,881000.0,0.000000
63,0.0,Estonie,2013,1287000.0,0.000000
244,0.0,Samoa,2013,190000.0,0.000000
128,0.0,Chine - RAS de Macao,2013,566000.0,0.000000
55,0.0,Dominique,2013,72000.0,0.000000
132,0.0,Maldives,2013,345000.0,0.000000
137,0.0,Maurice,2013,1244000.0,0.000000
14,0.0,Barbade,2013,285000.0,0.000000
50,0.0,Chypre,2013,1141000.0,0.000000
207,0.0,Suriname,2013,539000.0,0.000000
153,0.0,Nouvelle-Calédonie,2013,256000.0,0.000000
154,0.0,Macédoine du Nord,2013,2107000.0,0.000000
220,0.0,Trinité-et-Tobago,2013,1341000.0,0.000000
25,0.0,Îles Salomon,2013,561000.0,0.000000
155,0.0,Vanuatu,2013,253000.0,0.000000
26,0.0,Brunéi Darussalam,2013,418000.0,0.000000
83,0.0,Kiribati,2013,102000.0,0.000000
35,0.0,Cabo Verde,2013,499000.0,0.000000
191,0.0,Saint-Vincent-et-les Grenadines,2013,109000.0,0.000000
91,0.0,Guyana,2013,800000.0,0.000000

In [90]:
# Ajout d'une colonne dans la table 'sous_alim' permettant de repérer les pays les plus touchés par la sous-alimentation
dispo_alim['sous_alim_sup_20%'] = dispo_alim.Zone.isin(pays_sous_alim_sup20)

# Restriction de la table 'sous_alim' aux pays les plus touchés par la sous-alimentation
dispo_alim_sous_alim_sup = dispo_alim.loc[dispo_alim['sous_alim_sup_20%'] == True]

In [91]:
# Aggrégation de la table 'sous_alim' par produit
produits_export_sup = dispo_alim_sous_alim_sup.groupby('Produit').sum()

# Classement des 15 produits les plus exportés par les pays les plus touchés par la sous-alimentation et leurs quantités exportées (en milliers de tonnes)
produits_export_sup = produits_export_sup.nlargest(15, 'Exportations - Quantité')[['Exportations - Quantité']]
produits_export_sup

Empty DataFrame
Columns: [Exportations - Quantité]
Index: []

Les 15 produits les plus exportés par les pays touchés par la sous-alimentation sont dans l'ordre décroissant:
Riz (Eq Blanchi), Sucre Eq Brut, Blé, Fève de cacao, Noix, Maïs, Poissons Pelagiques, Alcool & non Comestible, Oranges & Mandarines, Légumes & Autres, Café, Soja, Sésame, Bananes, Pommes de Terre.

In [92]:
# Restriction de la table 'sous_alim' aux 15 produits les plus exportés par les pays touchés par la sous-alimentation
dispo_alim_15_prod_export_sup = dispo_alim.loc[(dispo_alim.Produit == 'Riz (Eq Blanchi)') | (dispo_alim.Produit == 'Sucre Eq Brut') | (dispo_alim.Produit == 'Blé') | (dispo_alim.Produit == 'Feve de Cacao') | (dispo_alim.Produit == 'Noix') | (dispo_alim.Produit == 'Maïs') | (dispo_alim.Produit == 'Poissons Pelagiques') | (dispo_alim.Produit == 'Alcool, non Comestible') | (dispo_alim.Produit == 'Oranges, Mandarines') | (dispo_alim.Produit == 'Légumes, Autres') | (dispo_alim.Produit == 'Café') | (dispo_alim.Produit == 'Soja') | (dispo_alim.Produit == 'Sésame') | (dispo_alim.Produit == 'Bananes') | (dispo_alim.Produit == 'Pommes de Terre')]

# Classement des 200 plus grandes importations de ces 15 produits
dispo_alim_200_prod_import_sup = dispo_alim_15_prod_export_sup.nlargest(200, 'Importations - Quantité')

# Aggrégation de ces importations par produit
dispo_alim_200_prod_import_agg_sup = dispo_alim_200_prod_import_sup.groupby('Produit').sum()
dispo_alim_200_prod_import_agg_sup

Élément,Population,Code Produit,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,...,Semences,Traitement,Variation de stock,Disponibilité alimentaire annuelle en Kcal,Disponibilité de protéines annuelle en Kg,Ratio Energie-Poids (kcal/kg),Ratio Protéines-Poids (%),is_cereal,sous_alimenté,sous_alim_sup_20%
Produit,,,,,,,,,,,,,,,,,,,,,
"Alcool, non Comestible",4.379600e+08,7977,0.0,2549.0,0.0,0.00,0.00,0.00,2549.0,2643.0,...,0.0,0.0,650.0,0.000000e+00,0.000000e+00,0.000000,0.000000,0.0,0.0,0.0
Bananes,7.472440e+08,15690,0.0,0.0,100.0,59.82,0.32,1.24,8441.0,2204.0,...,0.0,0.0,0.0,4.792115e+12,5.873188e+07,3660.033983,4.483849,0.0,0.0,0.0
Blé,4.637472e+09,140616,104403.0,18211.0,39156.0,5043.77,178.31,1186.93,486643.0,132726.0,...,22614.0,5982.0,-15146.0,9.275124e+14,2.855340e+10,157751.066893,473.186913,56.0,33.0,0.0
Café,4.027780e+08,5260,0.0,0.0,13.0,11.02,0.00,1.76,1926.0,1124.0,...,0.0,0.0,61.0,8.256559e+11,1.172450e+08,859.993061,11.841082,0.0,0.0,0.0
Feve de Cacao,4.195370e+08,7899,0.0,0.0,32.0,3.60,2.72,0.75,921.0,2079.0,...,0.0,0.0,146.0,2.328145e+12,6.918229e+07,17288.208169,24.525692,0.0,0.0,0.0
"Légumes, Autres",9.809330e+08,31260,3980.0,19.0,836.0,1046.13,6.86,39.21,87967.0,13923.0,...,30.0,160.0,17.0,2.012575e+13,9.738312e+08,3466.563867,16.045563,0.0,0.0,0.0
Maïs,3.479658e+09,90504,448615.0,182310.0,6585.0,798.74,58.92,159.11,765848.0,58493.0,...,3638.0,40211.0,-46270.0,1.885628e+14,4.419890e+09,101436.516769,231.972679,36.0,19.0,0.0
Noix,1.572191e+09,5102,0.0,0.0,43.0,6.35,3.51,1.27,3761.0,2203.0,...,0.0,0.0,97.0,8.085113e+12,2.266085e+08,4696.583427,13.306254,0.0,1.0,0.0
"Oranges, Mandarines",8.634760e+08,23499,0.0,1.0,182.0,287.81,0.54,3.05,21224.0,9994.0,...,0.0,0.0,-957.0,5.424861e+12,9.508786e+07,2292.318368,3.846626,0.0,0.0,0.0
Poissons Pelagiques,2.327322e+09,24867,13489.0,40.0,150.0,49.40,6.71,20.29,19539.0,6442.0,...,145.0,0.0,172.0,6.618150e+12,8.808701e+08,9517.159561,121.456271,0.0,4.0,0.0
Pommes de Terre,7.933770e+08,22779,1977.0,3464.0,1021.0,574.38,1.42,23.72,55673.0,21147.0,...,2935.0,887.0,1291.0,2.639933e+13,6.323724e+08,5808.081895,13.175200,0.0,0.0,0.0
Riz (Eq Blanchi),2.305283e+09,39270,12878.0,3199.0,6445.0,647.70,13.40,121.63,164665.0,4834.0,...,5012.0,812.0,-6283.0,5.061141e+14,9.247025e+09,51112.096731,96.535111,14.0,12.0,0.0
Soja,2.862398e+09,40880,13750.0,524.0,337.0,43.05,14.88,33.02,160345.0,41274.0,...,3596.0,133162.0,-4.0,2.579342e+13,2.423765e+09,27732.524731,378.909767,0.0,6.0,0.0
Sucre Eq Brut,4.397347e+09,58466,7.0,4076.0,6294.0,646.44,0.00,0.00,91711.0,10260.0,...,0.0,10493.0,-5319.0,2.750408e+14,0.000000e+00,81870.017243,0.000000,0.0,14.0,0.0

In [93]:
# Suppression des valeurs nulles des dénominateurs
dispo_alim_200_prod_import_agg_sup.drop(dispo_alim_200_prod_import_agg_sup.loc[(dispo_alim_200_prod_import_agg_sup['Disponibilité intérieure'] == 0)].index, inplace=True)
dispo_alim_200_prod_import_agg_sup.drop(dispo_alim_200_prod_import_agg_sup.loc[(dispo_alim_200_prod_import_agg_sup['Nourriture'] == 0)].index, inplace=True)

# Ajout d'une colonne désignant le ratio entre la quantité destinés aux "Autres utilisations" (Other uses) et la disponibilité intérieure
dispo_alim_200_prod_import_agg_sup['Ratio autres utilisations - disponinilité intérieure'] = (dispo_alim_200_prod_import_agg_sup.loc[:, 'Autres utilisations (non alimentaire)']) / (dispo_alim_200_prod_import_agg_sup.loc[:, 'Disponibilité intérieure']) * 100

# Ajout d'une colonne désignant le ratio entre la quantité destinée à la nourriture animale et la quantité destinée à la nourriture (animale + humaine)
dispo_alim_200_prod_import_agg_sup['Ratio nourriture animale - nourriture animale et humaine'] = (dispo_alim_200_prod_import_agg_sup.loc[:, 'Aliments pour animaux']) / ((dispo_alim_200_prod_import_agg_sup.loc[:, 'Aliments pour animaux']) + (dispo_alim_200_prod_import_agg_sup.loc[:, 'Nourriture'])) * 100

In [94]:
ratio_autres_utilisations_sup = dispo_alim_200_prod_import_agg_sup.nlargest(3, 'Ratio autres utilisations - disponinilité intérieure')
ratio_autres_utilisations_sup[['Ratio autres utilisations - disponinilité intérieure']]

Élément          Ratio autres utilisations - disponinilité intérieure
Produit
Maïs                                                     23.804985
Pommes de Terre                                           6.222047
Sucre Eq Brut                                             4.444396

#### Parmi les produits agricoles les plus exportés par les pays les plus touchés par la sous-alimentation, le maïs, les pommes de terre et le sucre sont les produits connaissant la part la plus forte d'utilisation diverses dans la disponibilité intérieure de leurs pays importateurs

In [95]:
ratio_nourriture_animale_sup = dispo_alim_200_prod_import_agg_sup.nlargest(3, 'Ratio nourriture animale - nourriture animale et humaine')
ratio_nourriture_animale_sup[['Ratio nourriture animale - nourriture animale et humaine']]

Élément              Ratio nourriture animale - nourriture animale et humaine
Produit
Maïs                                                         87.477965
Poissons Pelagiques                                          69.699788
Soja                                                         64.675447

#### Parmi les produits agricoles les plus exportés par les pays les plus touchés par la sous-alimentation, le maïs, les poissons pélagiques et le soja sont les produits les plus courrament destinés à l'alimentation animale

<a class='anchor' id='Question13'></a>
## Question 13: Combien de tonnes de céréales pourraient être libérées si les USA diminuaient de 10% la masse de produits destinés à l'alimentation animale?

In [96]:
# Restriction du tableau 'dispo_alim' aux données relatives à la production céréalières aux USA
alim_USA_cereal = dispo_alim.loc[(dispo_alim.Zone == "États-Unis d'Amérique") & (dispo_alim.is_cereal)]
alim_USA_cereal

Élément,Zone,Population,Code Produit,Produit,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Semences,Traitement,Variation de stock,Disponibilité alimentaire annuelle en Kcal,Disponibilité de protéines annuelle en Kg,Ratio Energie-Poids (kcal/kg),Ratio Protéines-Poids (%),is_cereal,sous_alimenté,sous_alim_sup_20%
15230,États-Unis d'Amérique,320051000.0,2511,Blé,Vegetaux,6196.0,16.0,599.0,80.43,2.85,...,2096.0,0.0,5284.0,6.997435e+13,2.260440e+09,2718.326495,8.781238,True,False,False
15231,États-Unis d'Amérique,320051000.0,2513,Orge,Vegetaux,1440.0,0.0,5.0,0.50,0.03,...,107.0,3161.0,16.0,5.840931e+11,1.635461e+07,3650.000000,10.220000,True,False,False
15232,États-Unis d'Amérique,320051000.0,2514,Maïs,Vegetaux,128024.0,137023.0,92.0,12.24,0.26,...,582.0,23230.0,-39863.0,1.074731e+13,1.950871e+08,2743.464052,4.979984,True,False,False
15233,États-Unis d'Amérique,320051000.0,2515,Seigle,Vegetaux,184.0,0.0,2.0,0.27,0.01,...,76.0,NaN,-76.0,2.336372e+11,8.177303e+06,2703.703704,9.462963,True,False,False
15234,États-Unis d'Amérique,320051000.0,2516,Avoine,Vegetaux,1430.0,NaN,19.0,3.95,0.31,...,103.0,NaN,32.0,2.219554e+12,9.228671e+07,1755.696203,7.300000,True,False,False
15235,États-Unis d'Amérique,320051000.0,2517,Millet,Vegetaux,394.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,False
15236,États-Unis d'Amérique,320051000.0,2518,Sorgho,Vegetaux,2351.0,NaN,7.0,0.74,0.07,...,22.0,1753.0,-3220.0,8.177303e+11,2.336372e+07,3452.702703,9.864865,True,False,False
15237,États-Unis d'Amérique,320051000.0,2520,"Céréales, Autres",Vegetaux,77.0,NaN,5.0,0.62,0.02,...,3.0,NaN,0.0,5.840931e+11,1.752279e+07,2943.548387,8.830645,True,False,False
15322,États-Unis d'Amérique,320051000.0,2805,Riz (Eq Blanchi),Vegetaux,NaN,142.0,72.0,6.88,0.08,...,109.0,464.0,-27.0,8.410940e+12,1.553688e+08,3819.767442,7.055959,True,False,False

In [97]:
# Calcul de la quantité de ceréales destinées à l'alimentation animale
alim_USA_cereal_animaux = alim_USA_cereal['Aliments pour animaux'].sum()

alim_USA_cereal_animaux_10pourcent = alim_USA_cereal_animaux/10

print(alim_USA_cereal_animaux_10pourcent)

14009.6

Si les USA libéraient de 10% la production de céréales destinées à l'alimentation animale, plus de 14 millions de tonnes de céréales pourraient être utilisées pour d'autres usages.

#### Calcul du nombre d'humains dont les besoins alimentaires pourraient être satisfaits par une libération de 10% de la production céréalière américaine destinée aux animaux

#### En besoins énergétiques (Kcal)

In [98]:
# Ajout d'une colonne dénombrant pour chaque produit la quantité d'énergie en Kcal qui serait libéré par 10% de la production céréalière américaine destinée aux animaux
alim_USA_cereal['Apport énergétique de 10% des céréales destinés aux animaux en kcal'] = alim_USA_cereal.loc[:, 'Aliments pour animaux'] / 10 * 1e6 * alim_USA_cereal.loc[:, 'Ratio Energie-Poids (kcal/kg)']
alim_USA_cereal

Élément,Zone,Population,Code Produit,Produit,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Traitement,Variation de stock,Disponibilité alimentaire annuelle en Kcal,Disponibilité de protéines annuelle en Kg,Ratio Energie-Poids (kcal/kg),Ratio Protéines-Poids (%),is_cereal,sous_alimenté,sous_alim_sup_20%,Apport énergétique de 10% des céréales destinés aux animaux en kcal
15230,États-Unis d'Amérique,320051000.0,2511,Blé,Vegetaux,6196.0,16.0,599.0,80.43,2.85,...,0.0,5284.0,6.997435e+13,2.260440e+09,2718.326495,8.781238,True,False,False,1.684275e+12
15231,États-Unis d'Amérique,320051000.0,2513,Orge,Vegetaux,1440.0,0.0,5.0,0.50,0.03,...,3161.0,16.0,5.840931e+11,1.635461e+07,3650.000000,10.220000,True,False,False,5.256000e+11
15232,États-Unis d'Amérique,320051000.0,2514,Maïs,Vegetaux,128024.0,137023.0,92.0,12.24,0.26,...,23230.0,-39863.0,1.074731e+13,1.950871e+08,2743.464052,4.979984,True,False,False,3.512292e+13
15233,États-Unis d'Amérique,320051000.0,2515,Seigle,Vegetaux,184.0,0.0,2.0,0.27,0.01,...,NaN,-76.0,2.336372e+11,8.177303e+06,2703.703704,9.462963,True,False,False,4.974815e+10
15234,États-Unis d'Amérique,320051000.0,2516,Avoine,Vegetaux,1430.0,NaN,19.0,3.95,0.31,...,NaN,32.0,2.219554e+12,9.228671e+07,1755.696203,7.300000,True,False,False,2.510646e+11
15235,États-Unis d'Amérique,320051000.0,2517,Millet,Vegetaux,394.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,True,False,False,NaN
15236,États-Unis d'Amérique,320051000.0,2518,Sorgho,Vegetaux,2351.0,NaN,7.0,0.74,0.07,...,1753.0,-3220.0,8.177303e+11,2.336372e+07,3452.702703,9.864865,True,False,False,8.117304e+11
15237,États-Unis d'Amérique,320051000.0,2520,"Céréales, Autres",Vegetaux,77.0,NaN,5.0,0.62,0.02,...,NaN,0.0,5.840931e+11,1.752279e+07,2943.548387,8.830645,True,False,False,2.266532e+10
15322,États-Unis d'Amérique,320051000.0,2805,Riz (Eq Blanchi),Vegetaux,NaN,142.0,72.0,6.88,0.08,...,464.0,-27.0,8.410940e+12,1.553688e+08,3819.767442,7.055959,True,False,False,NaN

In [99]:
alim_USA_cereal_animaux_10pourcent_Kcal = alim_USA_cereal['Apport énergétique de 10% des céréales destinés aux animaux en kcal'].sum()

# Calcul du nombre d'humains auxquels cette part de la production céréalière pourrait répondre en terme de besoins énergétiques
alim_USA_cereal_animaux_10pourcent_Kcal = alim_USA_cereal_animaux_10pourcent_Kcal / besoin_energ_min
alim_USA_cereal_animaux_10pourcent_Kcal

52695900.97597239

In [100]:
pop_nourrie_alim_USA_cereal_animaux_10pourcent_Kcal = alim_USA_cereal_animaux_10pourcent_Kcal / population_mondiale * 100
pop_nourrie_alim_USA_cereal_animaux_10pourcent_Kcal

0.7530862643240059

10% de la production céréalière américaine destinée aux animaux pourrait répondre aux besoins énergétiques de 52 695 900 habitants, soit 0,75% de la population mondiale

#### En besoin de protéines

In [101]:
# Ajout d'une colonne dénombrant la quantité de protéines qui serait libérée par 10% de la production céréalière américaine destinée aux animaux
alim_USA_cereal['Apport en protéines de 10% des céréales destinés aux animaux'] = alim_USA_cereal.loc[:, 'Aliments pour animaux'] / 10 * 1e9 * alim_USA_cereal.loc[:, 'Ratio Protéines-Poids (%)'] / 100
alim_USA_cereal

Élément,Zone,Population,Code Produit,Produit,Origine,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),...,Variation de stock,Disponibilité alimentaire annuelle en Kcal,Disponibilité de protéines annuelle en Kg,Ratio Energie-Poids (kcal/kg),Ratio Protéines-Poids (%),is_cereal,sous_alimenté,sous_alim_sup_20%,Apport énergétique de 10% des céréales destinés aux animaux en kcal,Apport en protéines de 10% des céréales destinés aux animaux
15230,États-Unis d'Amérique,320051000.0,2511,Blé,Vegetaux,6196.0,16.0,599.0,80.43,2.85,...,5284.0,6.997435e+13,2.260440e+09,2718.326495,8.781238,True,False,False,1.684275e+12,5.440855e+10
15231,États-Unis d'Amérique,320051000.0,2513,Orge,Vegetaux,1440.0,0.0,5.0,0.50,0.03,...,16.0,5.840931e+11,1.635461e+07,3650.000000,10.220000,True,False,False,5.256000e+11,1.471680e+10
15232,États-Unis d'Amérique,320051000.0,2514,Maïs,Vegetaux,128024.0,137023.0,92.0,12.24,0.26,...,-39863.0,1.074731e+13,1.950871e+08,2743.464052,4.979984,True,False,False,3.512292e+13,6.375574e+11
15233,États-Unis d'Amérique,320051000.0,2515,Seigle,Vegetaux,184.0,0.0,2.0,0.27,0.01,...,-76.0,2.336372e+11,8.177303e+06,2703.703704,9.462963,True,False,False,4.974815e+10,1.741185e+09
15234,États-Unis d'Amérique,320051000.0,2516,Avoine,Vegetaux,1430.0,NaN,19.0,3.95,0.31,...,32.0,2.219554e+12,9.228671e+07,1755.696203,7.300000,True,False,False,2.510646e+11,1.043900e+10
15235,États-Unis d'Amérique,320051000.0,2517,Millet,Vegetaux,394.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,True,False,False,NaN,NaN
15236,États-Unis d'Amérique,320051000.0,2518,Sorgho,Vegetaux,2351.0,NaN,7.0,0.74,0.07,...,-3220.0,8.177303e+11,2.336372e+07,3452.702703,9.864865,True,False,False,8.117304e+11,2.319230e+10
15237,États-Unis d'Amérique,320051000.0,2520,"Céréales, Autres",Vegetaux,77.0,NaN,5.0,0.62,0.02,...,0.0,5.840931e+11,1.752279e+07,2943.548387,8.830645,True,False,False,2.266532e+10,6.799597e+08
15322,États-Unis d'Amérique,320051000.0,2805,Riz (Eq Blanchi),Vegetaux,NaN,142.0,72.0,6.88,0.08,...,-27.0,8.410940e+12,1.553688e+08,3819.767442,7.055959,True,False,False,NaN,NaN

In [102]:
alim_USA_cereal_animaux_10pourcent_prot = alim_USA_cereal['Apport en protéines de 10% des céréales destinés aux animaux'].sum()

# Calcul du nombre d'humains auxquels cette part de la production céréalière pourrait répondre en terme de protéines
alim_USA_cereal_animaux_10pourcent_prot = alim_USA_cereal_animaux_10pourcent_prot / besoin_prot_min
alim_USA_cereal_animaux_10pourcent_prot

39091327.528594255

In [103]:
pop_nourrie_alim_USA_cereal_animaux_10pourcent_prot = alim_USA_cereal_animaux_10pourcent_prot / population_mondiale * 100
pop_nourrie_alim_USA_cereal_animaux_10pourcent_prot

0.5586609446036136

10% de la production céréalière américaine destinée aux animaux pourrait répondre aux besoins en protéines de 39 091 327 habitants, soit 0,56% de la population mondiale

<a class='anchor' id='Question14'></a>
## Question 14: En Thaïlande, quelle proportion de manioc est exportée et quelle est la proportion de personnes en sous-nutrtion?

In [104]:
# Part de manioc exportée dans la production de la Thaïlande
part_export_manioc_thai = (dispo_alim['Exportations - Quantité'].loc[(dispo_alim.Produit == 'Manioc') & (dispo_alim.Zone == 'Thaïlande')]) / (dispo_alim.Production.loc[(dispo_alim.Produit == 'Manioc') & (dispo_alim.Zone == 'Thaïlande')]) * 100
print(part_export_manioc_thai)

13658    83.41273
dtype: float64

#### 83,4 % du manioc produit en Thaïlande est exporté vers l'étranger.

In [105]:
part_pop_sous_alim_thai = int(sous_alim.Population.loc[(sous_alim.Zone == 'Thaïlande') & (sous_alim.Année == '2012-2014')]) / int(population.Population.loc[population.Zone == 'Thaïlande']) * 100
print(part_pop_sous_alim_thai)

8.356836937219263

#### Environ 8,4% de la population thaïlandaise était en sous-nutrition en 2013.

<a class='anchor' id='Question15'></a>
## Question 15: Proposez une clé primaire pertinente pour la table 'population'

In [106]:
population.rename(columns = {'Code zone': 'code_pays'}, inplace=True)
population.rename(columns = {'Zone': 'pays'}, inplace=True)
population.rename(columns = {'Année': 'annee'}, inplace=True)
population.rename(columns = {'Population': 'population'}, inplace=True)
population

     code_pays                                    pays  annee   population
0            2                             Afghanistan   2013   30552000.0
1          202                          Afrique du Sud   2013   52776000.0
2            3                                 Albanie   2013    3173000.0
3            4                                 Algérie   2013   39208000.0
4           79                               Allemagne   2013   82727000.0
5            7                                  Angola   2013   21472000.0
6            8                      Antigua-et-Barbuda   2013      90000.0
7          194                         Arabie saoudite   2013   28829000.0
8            9                               Argentine   2013   41446000.0
9            1                                 Arménie   2013    2977000.0
10          10                               Australie   2013   23343000.0
11          11                                Autriche   2013    8495000.0
12          52                             Azerbaïdjan   2013    9413000.0
13          12                                 Bahamas   2013     377000.0
14          16                              Bangladesh   2013  156595000.0
15          14                                 Barbade   2013     285000.0
16          57                                 Bélarus   2013    9357000.0
17         255                                Belgique   2013   11104000.0
18          23                                  Belize   2013     332000.0
19          53                                   Bénin   2013   10323000.0
20          17                                Bermudes   2013      65000.0
21          19         Bolivie (État plurinational de)   2013   10671000.0
22          80                      Bosnie-Herzégovine   2013    3829000.0
23          20                                Botswana   2013    2021000.0
24          21                                  Brésil   2013  200362000.0
25          26                       Brunéi Darussalam   2013     418000.0
26          27                                Bulgarie   2013    7223000.0
27         233                            Burkina Faso   2013   16935000.0
28          35                              Cabo Verde   2013     499000.0
29         115                                Cambodge   2013   15135000.0
..         ...                                     ...    ...          ...
145        244                                   Samoa   2013     190000.0
146        193                    Sao Tomé-et-Principe   2013     193000.0
147        195                                 Sénégal   2013   14133000.0
148        272                                  Serbie   2013    9511000.0
149        197                            Sierra Leone   2013    6092000.0
150        199                               Slovaquie   2013    5450000.0
151        198                                Slovénie   2013    2072000.0
152        276                                  Soudan   2013   37964000.0
153         38                               Sri Lanka   2013   21273000.0
154        210                                   Suède   2013    9571000.0
155        211                                  Suisse   2013    8078000.0
156        207                                Suriname   2013     539000.0
157        208                             Tadjikistan   2013    8208000.0
158         39                                   Tchad   2013   12825000.0
159        167                           Tchéquie (la)   2013   10702000.0
160        216                               Thaïlande   2013   67011000.0
161        176                             Timor-Leste   2013    1133000.0
162        217                                    Togo   2013    6817000.0
163        220                       Trinité-et-Tobago   2013    1341000.0
164        222                                 Tunisie   2013   10997000.0
165        213                            Turkménistan   2013    5240000.0
166        223                                 Turquie   2013   74933000.0
167        230                                 Ukraine   2013   45239000.0
168        234                                 Uruguay   2013    3407000.0
169        155                                 Vanuatu   2013     253000.0
170        236  Venezuela (République bolivarienne du)   2013   30405000.0
171        237                                Viet Nam   2013   91680000.0
172        249                                   Yémen   2013   24407000.0
173        251                                  Zambie   2013   14539000.0
174        181                                Zimbabwe   2013   14150000.0

[174 rows x 4 columns]

#### La colonne 'code_pays' semble être la clé primaire la plus pertinente

<a class='anchor' id='Question16'></a>
## Question 16: Proposez une clé primaire pertinente pour la table dispo_alimentaire

In [107]:
#Création d'une table pivot à partir de la table 'alimentation'
dispo_alimentaire = alimentation.pivot_table('Valeur', ['Zone', 'Code zone', 'Année', 'Produit', 'Code Produit', 'Origine', 'Population'], 'Élément', aggfunc="sum").reset_index()

# Intitulés de colonnes renommés
dispo_alimentaire.rename(columns = {'Zone': 'pays'}, inplace=True)
dispo_alimentaire.rename(columns = {'Code zone': 'code_pays'}, inplace=True)
dispo_alimentaire.rename(columns = {'Année': 'annee'}, inplace=True)
dispo_alimentaire.rename(columns = {'Produit': 'produit'}, inplace=True)
dispo_alimentaire.rename(columns = {'Code Produit': 'code_produit'}, inplace=True)
dispo_alimentaire.rename(columns = {'Origine': 'origin'}, inplace=True)
dispo_alimentaire.rename(columns = {'Disponibilité alimentaire (Kcal/personne/jour)': 'dispo_alim_kcal_p_j'}, inplace=True)
dispo_alimentaire.rename(columns = {'Disponibilité de protéines en quantité (g/personne/jour)': 'dispo_prot'}, inplace=True)
dispo_alimentaire.rename(columns = {'Disponibilité de matière grasse en quantité (g/personne/jour)': 'dispo_mat_gr '}, inplace=True)

# Conversion de la colonne rapportant la disponibilité alimentaire en kg/personne/jour en disponibilité alimentaire en Tonnes/an:
dispo_alimentaire['dispo_alim_tonnes'] = dispo_alimentaire.loc[:, 'Disponibilité alimentaire en quantité (kg/personne/an)'] * dispo_alimentaire.loc[:, 'Population'] / 1e3

# Suppression des colonnes inutiles
dispo_alimentaire.drop(columns=['Aliments pour animaux', 'Autres utilisations (non alimentaire)', 'Disponibilité alimentaire en quantité (kg/personne/an)', 'Disponibilité intérieure', 'Exportations - Quantité', 'Importations - Quantité', 'Nourriture', 'Pertes', 'Population', 'Production', 'Semences', 'Traitement', 'Variation de stock'], inplace=True)
dispo_alimentaire.head()

Élément,pays,code_pays,annee,produit,code_produit,origin,dispo_alim_kcal_p_j,dispo_mat_gr,dispo_prot,dispo_alim_tonnes
0,Afghanistan,2,2013,Abats Comestible,2736,Animaux,5.0,0.20,0.77,52549.44
1,Afghanistan,2,2013,"Agrumes, Autres",2614,Vegetaux,1.0,0.01,0.02,39412.08
2,Afghanistan,2,2013,Aliments pour enfants,2680,Vegetaux,1.0,0.01,0.03,1833.12
3,Afghanistan,2,2013,Ananas,2618,Vegetaux,0.0,NaN,NaN,0.00
4,Afghanistan,2,2013,Bananes,2615,Vegetaux,4.0,0.02,0.05,82490.40

#### L'association des colonnes 'pays' et 'produit' semble pouvoir constituer une clé primaire pertinente.

<a class='anchor' id='Question17'></a>
## Question 17: Proposez une clé primaire pertinente pour la table 'equilibre_prod'

In [108]:
#Création d'une table pivot à partir de la table 'alimentation'
equilibre_prod  = alimentation.pivot_table('Valeur', ['Zone', 'Code zone', 'Année', 'Produit', 'Code Produit'], 'Élément', aggfunc="sum").reset_index()

# Intitulés de colonnes renommés
equilibre_prod.rename(columns = {'Zone': 'pays'}, inplace=True)
equilibre_prod.rename(columns = {'Code zone': 'code_pays'}, inplace=True)
equilibre_prod.rename(columns = {'Année': 'annee'}, inplace=True)
equilibre_prod.rename(columns = {'Produit': 'produit'}, inplace=True)
equilibre_prod.rename(columns = {'Code Produit': 'code_produit'}, inplace=True)
equilibre_prod.rename(columns = {'Disponibilité intérieure': 'dispo_int'}, inplace=True)
equilibre_prod.rename(columns = {'Aliments pour animaux': 'alim_ani'}, inplace=True)
equilibre_prod.rename(columns = {'Semences': 'semences'}, inplace=True)
equilibre_prod.rename(columns = {'Pertes': 'pertes'}, inplace=True)
equilibre_prod.rename(columns = {'Traitement' : 'transfo'}, inplace=True)
equilibre_prod.rename(columns = {'Nourriture': 'nourriture'}, inplace=True)
equilibre_prod.rename(columns = {'Autres utilisations (non alimentaire)': 'autres_utilisations'}, inplace=True)

# Suppression de colonnes inutiles
equilibre_prod.drop(columns=['Disponibilité alimentaire (Kcal/personne/jour)', 'Disponibilité alimentaire en quantité (kg/personne/an)', 'Disponibilité de matière grasse en quantité (g/personne/jour)', 'Disponibilité de protéines en quantité (g/personne/jour)', 'Exportations - Quantité', 'Importations - Quantité', 'Production', 'Variation de stock'], inplace=True)
equilibre_prod.head()

Élément,pays,code_pays,annee,produit,code_produit,alim_ani,autres_utilisations,dispo_int,nourriture,pertes,semences,transfo
0,Afghanistan,2,2013,Abats Comestible,2736,NaN,NaN,53.0,53.0,NaN,NaN,NaN
1,Afghanistan,2,2013,"Agrumes, Autres",2614,NaN,NaN,41.0,39.0,2.0,NaN,NaN
2,Afghanistan,2,2013,Aliments pour enfants,2680,NaN,NaN,2.0,2.0,NaN,NaN,NaN
3,Afghanistan,2,2013,Ananas,2618,NaN,NaN,0.0,0.0,NaN,NaN,NaN
4,Afghanistan,2,2013,Bananes,2615,NaN,NaN,82.0,82.0,NaN,NaN,NaN

#### L'association des colonnes 'pays' et 'produit' semble pouvoir constituer une clé primaire pertinente.

<a class='anchor' id='Question18'></a>
## Question 18: Proposez une clé pour la table 'sous_nutrition'

In [109]:
sous_nutrition = sous_alim

# Intitulés de colonnes renommés
sous_nutrition.rename(columns = {'Zone': 'pays'}, inplace=True)
sous_nutrition.rename(columns = {'Code zone': 'code_pays'}, inplace=True)
sous_nutrition.rename(columns = {'Année': 'annee'}, inplace=True)
sous_nutrition.rename(columns = {'Population': 'nb_personnes'}, inplace=True)

sous_nutrition.head()

   code_pays         pays      annee  nb_personnes
0          2  Afghanistan  2012-2014     7900000.0
1          2  Afghanistan  2013-2015     8800000.0
2          2  Afghanistan  2014-2016     9600000.0
3          2  Afghanistan  2015-2017    10200000.0
4          2  Afghanistan  2016-2018    10600000.0

#### L'association des colonnes 'pays' et 'annee' semble pouvoir constituer une clé primaire pertinente.

In [110]:
# Création d'une fonction à 2 arguments testant les clefs primaires
def key_test(df_test, candidate_key):
    if len(df_test[candidate_key]) == len(df_test[candidate_key].drop_duplicates().dropna()):
        print('{} peut être la clé primaire du DataFrame.'.format(candidate_key))
    else:
        print('{} ne peut pas être la clé primaire du DataFrame'.format(candidate_key))
    
key_test(dispo_alimentaire, ['pays', 'produit'])

['pays', 'produit'] peut être la clé primaire du DataFrame.

<a class='anchor' id='Question19'></a>
## Question 19: Écrivez des requêtes SQL

In [111]:
# Enregistrement des tables au format CSV
population.to_csv("population.csv", index = False)
dispo_alimentaire.to_csv("dispo_alimentaire.csv", index = False)
equilibre_prod.to_csv("equilibre_prod.csv", index = False)
sous_nutrition.to_csv("sous_nutrition.csv", index = False)

#### Les 10 pays ayant le plus haut ratio disponibilité alimentaire/habitant en termes de protéines (en kg)

In [112]:
SELECT 
    disp.pays,
    ROUND(sum(disp.dispo_prot / 1e3), 3) AS ratio_dispo_prot_kg_p_j
FROM 
    dispo_alimentaire disp
GROUP BY
    disp.pays
ORDER BY
    ratio_dispo_prot_kg_p_j DESC
Limit 10;

IndentationError: unexpected indent (<ipython-input-112-1b91251ae486>, line 2)

#### Les 10 pays ayant le plus haut ratio disponibilité alimentaire/habitant en termes de kcal

In [ ]:
SELECT 
    disp.pays,
    sum(disp.dispo_alim_kcal_p_j) AS ratio_dispo_kcal_p_j
FROM 
    dispo_alimentaire disp
GROUP BY
    disp.pays
ORDER BY
    ratio_dispo_kcal_p_j DESC
Limit 10;

#### Pour l'année 2013, les 10 pays ayant le plus faible ratio disponibilité alimentaire/habitant en termes de protéines (en kg)

In [ ]:
SELECT 
    disp.pays,
    ROUND(sum(disp.dispo_prot / 1e3), 3) AS ratio_dispo_prot_kg_p_j
FROM 
    dispo_alimentaire disp
GROUP BY
    disp.pays
ORDER BY
    ratio_dispo_prot_kg_p_j ASC
LIMIT 10;

#### La quantité totale (en kg) de produits perdus par pays en 2013.

In [ ]:
SELECT 
    eq.pays,
    (sum(eq.pertes) * 1e6) AS produits_perdus_kg
FROM
    equilibre_prod eq
GROUP BY
    eq.pays;

#### Les 10 pays pour lesquels la proportion de personnes sous-alimentées est la plus forte.

In [ ]:
SELECT 
    s_n.pays,
    s_n.annee,
    ROUND((CAST(s_n.nb_personnes AS float) / CAST(pop.population AS float) * 100), 2) AS part_population_sous_alimentée
FROM
    population pop
    LEFT OUTER JOIN sous_nutrition s_n ON pop.pays = s_n.pays 
WHERE 
    s_n.annee = '2012-2014' AND
    pop.annee = 2013
GROUP BY
    s_n.pays
ORDER BY
    part_population_sous_alimentée DESC
LIMIT 10;

#### Les 10 produits pour lesquels le ratio Autres utilisations/Disponibilité intérieure est le plus élevé.

In [ ]:
SELECT 
    eq.produit, 
    ROUND((sum(eq.autres_utilisations) / sum(eq.dispo_int) * 100), 2) AS ratio_autres_util_dispo_inter
FROM
    equilibre_prod eq
GROUP BY
    eq.produit
ORDER BY
    ratio_autres_util_dispo_inter DESC
LIMIT 10;

<a class='anchor' id='Question20'></a>
## Question 20: Supposez quelles sont les "autres utilisations" possibles?

- Les usages d’ordre non-alimentaire (produits cosmétiques et pharmaceutiques)
- Les agro-carburants qui représentent une part croissante de la production agricole
- Quantités de produits consommés par les touristes (pour garantir la corrélation entre la disponibilité alimentaire et la consommation nationale)